(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about~course_$courseName~course_$courseName$93_skill_$91id~development~devtools~license~login~sign$4~650be18c"],{

/***/ "../lluis/Icon.svelte":
/*!****************************!*\
  !*** ../lluis/Icon.svelte ***!
  \****************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Icon.svelte generated by Svelte v3.25.0 */


const file = "home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Icon.svelte";

function create_fragment(ctx) {
	let span;
	let i;
	let i_class_value;
	let span_class_value;

	const block = {
		c: function create() {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			this.h();
		},
		l: function claim(nodes) {
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", i_class_value = `${/*prefix*/ ctx[1]} fa-${/*icon*/ ctx[2]} ${/*size*/ ctx[0] === "large" ? "fa-2x" : ""}`);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 8, 2, 181);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", span_class_value = `icon is-${/*size*/ ctx[0]}`);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span, "is-left", /*left*/ ctx[3]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 7, 0, 121);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*prefix, icon, size*/ 7 && i_class_value !== (i_class_value = `${/*prefix*/ ctx[1]} fa-${/*icon*/ ctx[2]} ${/*size*/ ctx[0] === "large" ? "fa-2x" : ""}`)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", i_class_value);
			}

			if (dirty & /*size*/ 1 && span_class_value !== (span_class_value = `icon is-${/*size*/ ctx[0]}`)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", span_class_value);
			}

			if (dirty & /*size, left*/ 9) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(span, "is-left", /*left*/ ctx[3]);
			}
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Icon", slots, []);
	let { size = "medium" } = $$props;
	let { prefix = "fas" } = $$props;
	let { icon } = $$props;
	let { left = false } = $$props;
	const writable_props = ["size", "prefix", "icon", "left"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Icon> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("size" in $$props) $$invalidate(0, size = $$props.size);
		if ("prefix" in $$props) $$invalidate(1, prefix = $$props.prefix);
		if ("icon" in $$props) $$invalidate(2, icon = $$props.icon);
		if ("left" in $$props) $$invalidate(3, left = $$props.left);
	};

	$$self.$capture_state = () => ({ size, prefix, icon, left });

	$$self.$inject_state = $$props => {
		if ("size" in $$props) $$invalidate(0, size = $$props.size);
		if ("prefix" in $$props) $$invalidate(1, prefix = $$props.prefix);
		if ("icon" in $$props) $$invalidate(2, icon = $$props.icon);
		if ("left" in $$props) $$invalidate(3, left = $$props.left);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [size, prefix, icon, left];
}

class Icon extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { size: 0, prefix: 1, icon: 2, left: 3 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Icon",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*icon*/ ctx[2] === undefined && !("icon" in props)) {
			console.warn("<Icon> was created without expected prop 'icon'");
		}
	}

	get size() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set size(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get prefix() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set prefix(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get icon() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set icon(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get left() {
		throw new Error("<Icon>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set left(value) {
		throw new Error("<Icon>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Icon);

/***/ }),

/***/ "./src/components/GitHubButton.svelte":
/*!********************************************!*\
  !*** ./src/components/GitHubButton.svelte ***!
  \********************************************/
/*! exports provided: default, preload */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preload", function() { return preload; });
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var lluis_Icon__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! lluis/Icon */ "../lluis/Icon.svelte");
/* harmony import */ var lluis_Button__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! lluis/Button */ "../lluis/Button.svelte");
/* src/components/GitHubButton.svelte generated by Svelte v3.25.0 */





const file = "src/components/GitHubButton.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-29uuok-style";
	style.textContent = "@keyframes svelte-29uuok-spinAround{from{transform:rotate(0deg)}to{transform:rotate(359deg)}}.tag.svelte-29uuok.svelte-29uuok{color:inherit !important;padding-left:0;background:transparent !important}.tag.svelte-29uuok .stars.svelte-29uuok{padding-top:0.1em;font-family:monospace}.tag.svelte-29uuok .icon.svelte-29uuok{margin-left:0 !important}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiR2l0SHViQnV0dG9uLnN2ZWx0ZSIsInNvdXJjZXMiOlsiR2l0SHViQnV0dG9uLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9XCJtb2R1bGVcIj5cbiAgZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHByZWxvYWQocGFnZSkge1xuICAgIGNvbnN0IHJlcG8gPSBhd2FpdCBmZXRjaChcImh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vcmVwb3Mva2FudG9yZC9MaWJyZUxpbmdvXCIpXG5cbiAgICBjb25zdCB7IHN0YXJnYXplcnNfY291bnQgfSA9IGF3YWl0IHJlcG8uanNvbigpXG4gICAgcmV0dXJuIHtcbiAgICAgIHN0YXJnYXplcnNfY291bnQsXG4gICAgfVxuICB9XG48L3NjcmlwdD5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIlxuICBpbXBvcnQgSWNvbiBmcm9tIFwibGx1aXMvSWNvblwiXG4gIGltcG9ydCBCdXR0b24gZnJvbSBcImxsdWlzL0J1dHRvblwiXG4gIGNvbnN0IHBNZW1vaXplID0gcmVxdWlyZShcInAtbWVtb2l6ZVwiKVxuICBleHBvcnQgbGV0IHN0YXJzID0gKHByb2Nlc3MuYnJvd3NlciA9PT0gdHJ1ZSA/IHdpbmRvdy5zdGFycyA6IG51bGwpIHx8IFwiICAgXCJcbiAgZXhwb3J0IGxldCBzaXplID0gXCJzbWFsbFwiXG5cbiAgb25Nb3VudChhc3luYyAoKSA9PiB7XG4gICAgaWYgKHByb2Nlc3MuYnJvd3NlciA9PT0gdHJ1ZSAmJiB3aW5kb3cuaXNDeXByZXNzKSB7XG4gICAgICBzdGFycyA9IDk5OVxuICAgICAgcmV0dXJuXG4gICAgfVxuXG4gICAgcE1lbW9pemUoZmV0Y2gsIHsgbWF4QWdlOiA1ICogNjAgKiAxMDAwIH0pKFxuICAgICAgXCJodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zL2thbnRvcmQvTGlicmVMaW5nb1wiXG4gICAgKVxuICAgICAgLnRoZW4oKHJlcykgPT4gcmVzLmpzb24oKSlcbiAgICAgIC50aGVuKCh7IHN0YXJnYXplcnNfY291bnQgfSkgPT4ge1xuICAgICAgICBzdGFycyA9IHN0YXJnYXplcnNfY291bnRcbiAgICAgICAgaWYgKHByb2Nlc3MuYnJvd3NlciA9PT0gdHJ1ZSkge1xuICAgICAgICAgIHdpbmRvdy5zdGFyX2NvdW50ID0gc3RhcmdhemVyc19jb3VudFxuICAgICAgICB9XG4gICAgICB9KVxuICB9KVxuPC9zY3JpcHQ+XG5cbjxCdXR0b25cbiAgdGFyZ2V0PVwiX2JsYW5rXCJcbiAgb3V0bGluZWRcbiAgaW52ZXJ0ZWRcbiAgaW5mb1xuICB7c2l6ZX1cbiAgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9rYW50b3JkL0xpYnJlTGluZ29cIj5cbiAgeyNpZiBzdGFyc31cbiAgICA8c3BhbiBjbGFzcz1cInRhZyBpcy13aGl0ZVwiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJzdGFyc1wiPntzdGFyc308L3NwYW4+XG4gICAgICA8c3BhbiBjbGFzcz1cImljb25cIj5cbiAgICAgICAgPEljb24gaWNvbj1cInN0YXJcIiAvPlxuICAgICAgPC9zcGFuPlxuICAgIDwvc3Bhbj5cbiAgey9pZn1cbiAgPHNwYW4gY2xhc3M9XCJpcy1oaWRkZW4tbW9iaWxlXCI+R2l0SHViPC9zcGFuPlxuPC9CdXR0b24+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbi50YWcge1xuICBjb2xvcjogaW5oZXJpdCAhaW1wb3J0YW50O1xuICBwYWRkaW5nLWxlZnQ6IDA7XG4gIGJhY2tncm91bmQ6IHRyYW5zcGFyZW50ICFpbXBvcnRhbnQ7IH1cbiAgLnRhZyAuc3RhcnMge1xuICAgIHBhZGRpbmctdG9wOiAwLjFlbTtcbiAgICBmb250LWZhbWlseTogbW9ub3NwYWNlOyB9XG4gIC50YWcgLmljb24ge1xuICAgIG1hcmdpbi1sZWZ0OiAwICFpbXBvcnRhbnQ7IH1cbjwvc3R5bGU+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBd0RPLFdBQVcsd0JBQVcsQ0FBQyxBQUM1QixJQUFJLEFBQUMsQ0FBQyxBQUNKLFNBQVMsQ0FBRSxPQUFPLElBQUksQ0FBQyxBQUFFLENBQUMsQUFDNUIsRUFBRSxBQUFDLENBQUMsQUFDRixTQUFTLENBQUUsT0FBTyxNQUFNLENBQUMsQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUVsQyxJQUFJLDRCQUFDLENBQUMsQUFDSixLQUFLLENBQUUsT0FBTyxDQUFDLFVBQVUsQ0FDekIsWUFBWSxDQUFFLENBQUMsQ0FDZixVQUFVLENBQUUsV0FBVyxDQUFDLFVBQVUsQUFBRSxDQUFDLEFBQ3JDLGtCQUFJLENBQUMsTUFBTSxjQUFDLENBQUMsQUFDWCxXQUFXLENBQUUsS0FBSyxDQUNsQixXQUFXLENBQUUsU0FBUyxBQUFFLENBQUMsQUFDM0Isa0JBQUksQ0FBQyxLQUFLLGNBQUMsQ0FBQyxBQUNWLFdBQVcsQ0FBRSxDQUFDLENBQUMsVUFBVSxBQUFFLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (46:2) {#if stars}
function create_if_block(ctx) {
	let span2;
	let span0;
	let t0;
	let t1;
	let span1;
	let icon;
	let current;
	icon = new lluis_Icon__WEBPACK_IMPORTED_MODULE_2__["default"]({ props: { icon: "star" }, $$inline: true });

	const block = {
		c: function create() {
			span2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*stars*/ ctx[0]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			span2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span2);
			span0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span2_nodes, "SPAN", { class: true });
			var span0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span0);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span0_nodes, /*stars*/ ctx[0]);
			span0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(span2_nodes);
			span1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span2_nodes, "SPAN", { class: true });
			var span1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, span1_nodes);
			span1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span0, "class", "stars svelte-29uuok");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span0, file, 47, 6, 1136);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span1, "class", "icon svelte-29uuok");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span1, file, 48, 6, 1177);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span2, "class", "tag is-white svelte-29uuok");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span2, file, 46, 4, 1102);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span2, span0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span2, span1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, span1, null);
			current = true;
		},
		p: function update(ctx, dirty) {
			if (!current || dirty & /*stars*/ 1) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*stars*/ ctx[0]);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(46:2) {#if stars}",
		ctx
	});

	return block;
}

// (39:0) <Button   target="_blank"   outlined   inverted   info   {size}   href="https://github.com/kantord/LibreLingo">
function create_default_slot(ctx) {
	let t0;
	let span;
	let t1;
	let current;
	let if_block = /*stars*/ ctx[0] && create_if_block(ctx);

	const block = {
		c: function create() {
			if (if_block) if_block.c();
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GitHub");
			this.h();
		},
		l: function claim(nodes) {
			if (if_block) if_block.l(nodes);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, "GitHub");
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "is-hidden-mobile");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 53, 2, 1262);
		},
		m: function mount(target, anchor) {
			if (if_block) if_block.m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t1);
			current = true;
		},
		p: function update(ctx, dirty) {
			if (/*stars*/ ctx[0]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*stars*/ 1) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(t0.parentNode, t0);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if (if_block) if_block.d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(39:0) <Button   target=\\\"_blank\\\"   outlined   inverted   info   {size}   href=\\\"https://github.com/kantord/LibreLingo\\\">",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let button;
	let current;

	button = new lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				target: "_blank",
				outlined: true,
				inverted: true,
				info: true,
				size: /*size*/ ctx[1],
				href: "https://github.com/kantord/LibreLingo",
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, target, anchor);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			const button_changes = {};
			if (dirty & /*size*/ 2) button_changes.size = /*size*/ ctx[1];

			if (dirty & /*$$scope, stars*/ 9) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

async function preload(page) {
	const repo = await fetch("https://api.github.com/repos/kantord/LibreLingo");
	const { stargazers_count } = await repo.json();
	return { stargazers_count };
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("GitHubButton", slots, []);
	const pMemoize = __webpack_require__(/*! p-memoize */ "../../node_modules/p-memoize/index.js");
	let { stars = ( true ? window.stars : undefined) || "   " } = $$props;
	let { size = "small" } = $$props;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		if ( true && window.isCypress) {
			$$invalidate(0, stars = 999);
			return;
		}

		pMemoize(fetch, { maxAge: 5 * 60 * 1000 })("https://api.github.com/repos/kantord/LibreLingo").then(res => res.json()).then(({ stargazers_count }) => {
			$$invalidate(0, stars = stargazers_count);

			if (true) {
				window.star_count = stargazers_count;
			}
		});
	});

	const writable_props = ["stars", "size"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<GitHubButton> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("stars" in $$props) $$invalidate(0, stars = $$props.stars);
		if ("size" in $$props) $$invalidate(1, size = $$props.size);
	};

	$$self.$capture_state = () => ({
		preload,
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		Icon: lluis_Icon__WEBPACK_IMPORTED_MODULE_2__["default"],
		Button: lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"],
		pMemoize,
		stars,
		size
	});

	$$self.$inject_state = $$props => {
		if ("stars" in $$props) $$invalidate(0, stars = $$props.stars);
		if ("size" in $$props) $$invalidate(1, size = $$props.size);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [stars, size];
}

class GitHubButton extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-29uuok-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { stars: 0, size: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "GitHubButton",
			options,
			id: create_fragment.name
		});
	}

	get stars() {
		throw new Error("<GitHubButton>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set stars(value) {
		throw new Error("<GitHubButton>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get size() {
		throw new Error("<GitHubButton>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set size(value) {
		throw new Error("<GitHubButton>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (GitHubButton);


/***/ }),

/***/ "./src/components/NavBar.svelte":
/*!**************************************!*\
  !*** ./src/components/NavBar.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _settings__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../settings */ "./src/settings.js");
/* harmony import */ var _auth__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../auth */ "./src/auth.js");
/* harmony import */ var _GitHubButton__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ./GitHubButton */ "./src/components/GitHubButton.svelte");
/* harmony import */ var lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! lluis/Icon.svelte */ "../lluis/Icon.svelte");
/* harmony import */ var lluis_Button__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! lluis/Button */ "../lluis/Button.svelte");
/* src/components/NavBar.svelte generated by Svelte v3.25.0 */







const file = "src/components/NavBar.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-17yvxfi-style";
	style.textContent = "@keyframes svelte-17yvxfi-spinAround{from{transform:rotate(0deg)}to{transform:rotate(359deg)}}.navbar.dark.svelte-17yvxfi.svelte-17yvxfi{background:#325f74;color:#bfb5af}.navbar.svelte-17yvxfi.svelte-17yvxfi{border:0}.navbar.svelte-17yvxfi .navbar-end.svelte-17yvxfi{position:absolute;right:0;top:0}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTmF2QmFyLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTmF2QmFyLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBpbXBvcnQgc2V0dGluZ3MgZnJvbSBcIi4uL3NldHRpbmdzXCJcbiAgaW1wb3J0IGF1dGhTdG9yZSBmcm9tIFwiLi4vYXV0aFwiXG4gIGltcG9ydCBHaXRIdWJCdXR0b24gZnJvbSBcIi4vR2l0SHViQnV0dG9uXCJcbiAgaW1wb3J0IEljb24gZnJvbSBcImxsdWlzL0ljb24uc3ZlbHRlXCJcbiAgaW1wb3J0IEJ1dHRvbiBmcm9tIFwibGx1aXMvQnV0dG9uXCJcbiAgZXhwb3J0IGxldCBkYXJrID0gZmFsc2VcbiAgZXhwb3J0IGxldCBpc19oaWRkZW5fbW9iaWxlID0gZmFsc2VcbiAgZXhwb3J0IGxldCBoYXNBdXRoID0gZmFsc2Vcbjwvc2NyaXB0PlxuXG48bmF2XG4gIGNsYXNzPVwibmF2YmFyXCJcbiAgY2xhc3M6ZGFya1xuICBjbGFzczppcy1oaWRkZW4tbW9iaWxlPVwie2lzX2hpZGRlbl9tb2JpbGV9XCJcbiAgcm9sZT1cIm5hdmlnYXRpb25cIlxuICBhcmlhLWxhYmVsPVwibWFpbiBuYXZpZ2F0aW9uXCI+XG4gIDxkaXYgY2xhc3M9XCJuYXZiYXItYnJhbmRcIj5cbiAgICA8YSBjbGFzcz1cIm5hdmJhci1pdGVtXCIgaHJlZj1cIi9cIj5cbiAgICAgIDxpbWcgc3JjPVwiL2ltYWdlcy9sb2dvLnN2Z1wiIGFsdD1cIkxpYnJlTGluZ29cIiAvPlxuICAgIDwvYT5cbiAgPC9kaXY+XG5cbiAgPGRpdiBjbGFzcz1cIm5hdmJhci1zdGFydFwiPjwvZGl2PlxuXG4gIDxkaXYgY2xhc3M9XCJuYXZiYXItZW5kXCI+XG4gICAgPGRpdiBjbGFzcz1cIm5hdmJhci1pdGVtXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiYnV0dG9uc1wiPlxuICAgICAgICA8R2l0SHViQnV0dG9uIC8+XG4gICAgICAgIHsjaWYgaGFzQXV0aCAmJiBzZXR0aW5ncy5mZWF0dXJlcy5hdXRoRW5hYmxlZH1cbiAgICAgICAgICB7I2lmICRhdXRoU3RvcmUudXNlcn1cbiAgICAgICAgICAgIDxCdXR0b24gc2l6ZT1cInNtYWxsXCIgb3V0bGluZWQgaW52ZXJ0ZWQgaW5mbz5cbiAgICAgICAgICAgICAgPEljb24gc2l6ZT1cInNtYWxsXCIgaWNvbj1cInVzZXJcIiAvPlxuICAgICAgICAgICAgICA8c3Bhbj57JGF1dGhTdG9yZS51c2VyLm5hbWV9PC9zcGFuPlxuICAgICAgICAgICAgPC9CdXR0b24+XG4gICAgICAgICAgICA8QnV0dG9uXG4gICAgICAgICAgICAgIG9uOmNsaWNrPVwieygpID0+IHdpbmRvdy5fTG9nb3V0KCl9XCJcbiAgICAgICAgICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgICAgICAgICAgb3V0bGluZWRcbiAgICAgICAgICAgICAgaW52ZXJ0ZWRcbiAgICAgICAgICAgICAgaW5mbz5cbiAgICAgICAgICAgICAgTG9nIG91dFxuICAgICAgICAgICAgPC9CdXR0b24+XG4gICAgICAgICAgezplbHNlfVxuICAgICAgICAgICAgPEJ1dHRvbiBocmVmPVwiL3NpZ24tdXBcIiBzaXplPVwic21hbGxcIiBvdXRsaW5lZCBpbnZlcnRlZCBpbmZvPlxuICAgICAgICAgICAgICBTaWduIHVwXG4gICAgICAgICAgICA8L0J1dHRvbj5cbiAgICAgICAgICAgIDxCdXR0b24gaHJlZj1cIi9sb2dpblwiIHNpemU9XCJzbWFsbFwiIG91dGxpbmVkIGludmVydGVkIGluZm8+XG4gICAgICAgICAgICAgIExvZyBpblxuICAgICAgICAgICAgPC9CdXR0b24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgey9pZn1cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvbmF2PlxuXG48c3R5bGU+QGtleWZyYW1lcyBzcGluQXJvdW5kIHtcbiAgZnJvbSB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMGRlZyk7IH1cbiAgdG8ge1xuICAgIHRyYW5zZm9ybTogcm90YXRlKDM1OWRlZyk7IH0gfVxuXG4ubmF2YmFyLmRhcmsge1xuICBiYWNrZ3JvdW5kOiAjMzI1Zjc0O1xuICBjb2xvcjogI2JmYjVhZjsgfVxuXG4ubmF2YmFyIHtcbiAgYm9yZGVyOiAwOyB9XG4gIC5uYXZiYXIgLm5hdmJhci1lbmQge1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICByaWdodDogMDtcbiAgICB0b3A6IDA7IH1cbjwvc3R5bGU+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBeURPLFdBQVcseUJBQVcsQ0FBQyxBQUM1QixJQUFJLEFBQUMsQ0FBQyxBQUNKLFNBQVMsQ0FBRSxPQUFPLElBQUksQ0FBQyxBQUFFLENBQUMsQUFDNUIsRUFBRSxBQUFDLENBQUMsQUFDRixTQUFTLENBQUUsT0FBTyxNQUFNLENBQUMsQUFBRSxDQUFDLEFBQUMsQ0FBQyxBQUVsQyxPQUFPLEtBQUssOEJBQUMsQ0FBQyxBQUNaLFVBQVUsQ0FBRSxPQUFPLENBQ25CLEtBQUssQ0FBRSxPQUFPLEFBQUUsQ0FBQyxBQUVuQixPQUFPLDhCQUFDLENBQUMsQUFDUCxNQUFNLENBQUUsQ0FBQyxBQUFFLENBQUMsQUFDWixzQkFBTyxDQUFDLFdBQVcsZUFBQyxDQUFDLEFBQ25CLFFBQVEsQ0FBRSxRQUFRLENBQ2xCLEtBQUssQ0FBRSxDQUFDLENBQ1IsR0FBRyxDQUFFLENBQUMsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (30:8) {#if hasAuth && settings.features.authEnabled}
function create_if_block(ctx) {
	let current_block_type_index;
	let if_block;
	let if_block_anchor;
	let current;
	const if_block_creators = [create_if_block_1, create_else_block];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*$authStore*/ ctx[3].user) return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);

	const block = {
		c: function create() {
			if_block.c();
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		l: function claim(nodes) {
			if_block.l(nodes);
			if_block_anchor = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["empty"])();
		},
		m: function mount(target, anchor) {
			if_blocks[current_block_type_index].m(target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, if_block_anchor, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if_blocks[current_block_type_index].p(ctx, dirty);
			} else {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
				if_block = if_blocks[current_block_type_index];

				if (!if_block) {
					if_block = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block.c();
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
				if_block.m(if_block_anchor.parentNode, if_block_anchor);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if_blocks[current_block_type_index].d(detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(if_block_anchor);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(30:8) {#if hasAuth && settings.features.authEnabled}",
		ctx
	});

	return block;
}

// (44:10) {:else}
function create_else_block(ctx) {
	let button0;
	let t;
	let button1;
	let current;

	button0 = new lluis_Button__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				href: "/sign-up",
				size: "small",
				outlined: true,
				inverted: true,
				info: true,
				$$slots: { default: [create_default_slot_3] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button1 = new lluis_Button__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				href: "/login",
				size: "small",
				outlined: true,
				inverted: true,
				info: true,
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button0.$$.fragment);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button0.$$.fragment, nodes);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button0, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button0_changes = {};

			if (dirty & /*$$scope*/ 32) {
				button0_changes.$$scope = { dirty, ctx };
			}

			button0.$set(button0_changes);
			const button1_changes = {};

			if (dirty & /*$$scope*/ 32) {
				button1_changes.$$scope = { dirty, ctx };
			}

			button1.$set(button1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button0, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(44:10) {:else}",
		ctx
	});

	return block;
}

// (31:10) {#if $authStore.user}
function create_if_block_1(ctx) {
	let button0;
	let t;
	let button1;
	let current;

	button0 = new lluis_Button__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				size: "small",
				outlined: true,
				inverted: true,
				info: true,
				$$slots: { default: [create_default_slot_1] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button1 = new lluis_Button__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				size: "small",
				outlined: true,
				inverted: true,
				info: true,
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button1.$on("click", /*click_handler*/ ctx[4]);

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button0.$$.fragment);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button0.$$.fragment, nodes);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button0, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const button0_changes = {};

			if (dirty & /*$$scope, $authStore*/ 40) {
				button0_changes.$$scope = { dirty, ctx };
			}

			button0.$set(button0_changes);
			const button1_changes = {};

			if (dirty & /*$$scope*/ 32) {
				button1_changes.$$scope = { dirty, ctx };
			}

			button1.$set(button1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button0, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(31:10) {#if $authStore.user}",
		ctx
	});

	return block;
}

// (45:12) <Button href="/sign-up" size="small" outlined inverted info>
function create_default_slot_3(ctx) {
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Sign up");
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "Sign up");
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_3.name,
		type: "slot",
		source: "(45:12) <Button href=\\\"/sign-up\\\" size=\\\"small\\\" outlined inverted info>",
		ctx
	});

	return block;
}

// (48:12) <Button href="/login" size="small" outlined inverted info>
function create_default_slot_2(ctx) {
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Log in");
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "Log in");
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(48:12) <Button href=\\\"/login\\\" size=\\\"small\\\" outlined inverted info>",
		ctx
	});

	return block;
}

// (32:12) <Button size="small" outlined inverted info>
function create_default_slot_1(ctx) {
	let icon;
	let t0;
	let span;
	let t1_value = /*$authStore*/ ctx[3].user.name + "";
	let t1;
	let current;

	icon = new lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: { size: "small", icon: "user" },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon.$$.fragment);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t1_value);
			this.h();
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon.$$.fragment, nodes);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SPAN", {});
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(span_nodes, t1_value);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 33, 14, 927);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, span, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, t1);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*$authStore*/ 8) && t1_value !== (t1_value = /*$authStore*/ ctx[3].user.name + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t1, t1_value);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(span);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_1.name,
		type: "slot",
		source: "(32:12) <Button size=\\\"small\\\" outlined inverted info>",
		ctx
	});

	return block;
}

// (36:12) <Button               on:click="{() => window._Logout()}"               size="small"               outlined               inverted               info>
function create_default_slot(ctx) {
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Log out");
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "Log out");
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(36:12) <Button               on:click=\\\"{() => window._Logout()}\\\"               size=\\\"small\\\"               outlined               inverted               info>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let nav;
	let div0;
	let a;
	let img;
	let img_src_value;
	let t0;
	let div1;
	let t1;
	let div4;
	let div3;
	let div2;
	let githubbutton;
	let t2;
	let current;
	githubbutton = new _GitHubButton__WEBPACK_IMPORTED_MODULE_3__["default"]({ $$inline: true });
	let if_block = /*hasAuth*/ ctx[2] && _settings__WEBPACK_IMPORTED_MODULE_1__["default"].features.authEnabled && create_if_block(ctx);

	const block = {
		c: function create() {
			nav = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("nav");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(githubbutton.$$.fragment);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block) if_block.c();
			this.h();
		},
		l: function claim(nodes) {
			nav = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "NAV", {
				class: true,
				role: true,
				"aria-label": true
			});

			var nav_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(nav);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nav_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "A", { class: true, href: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "IMG", { src: true, alt: true });
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nav_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nav_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nav_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nav_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(githubbutton.$$.fragment, div2_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			if (if_block) if_block.l(div2_nodes);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			nav_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			if (img.src !== (img_src_value = "/images/logo.svg")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "src", img_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "alt", "LibreLingo");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 19, 6, 508);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "navbar-item");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 18, 4, 469);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "navbar-brand");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 17, 2, 438);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "navbar-start");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 23, 2, 577);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "buttons");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 27, 6, 674);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "navbar-item");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 26, 4, 642);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "navbar-end svelte-17yvxfi");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 25, 2, 613);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(nav, "class", "navbar svelte-17yvxfi");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(nav, "role", "navigation");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(nav, "aria-label", "main navigation");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(nav, "dark", /*dark*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(nav, "is-hidden-mobile", /*is_hidden_mobile*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(nav, file, 11, 0, 303);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, nav, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(nav, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(nav, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(nav, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(nav, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(nav, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(githubbutton, div2, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			if (if_block) if_block.m(div2, null);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (/*hasAuth*/ ctx[2] && _settings__WEBPACK_IMPORTED_MODULE_1__["default"].features.authEnabled) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*hasAuth*/ 4) {
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block, 1);
					if_block.m(div2, null);
				}
			} else if (if_block) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block, 1, 1, () => {
					if_block = null;
				});

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();
			}

			if (dirty & /*dark*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(nav, "dark", /*dark*/ ctx[0]);
			}

			if (dirty & /*is_hidden_mobile*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(nav, "is-hidden-mobile", /*is_hidden_mobile*/ ctx[1]);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(githubbutton.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(if_block);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(githubbutton.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(if_block);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(nav);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(githubbutton);
			if (if_block) if_block.d();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $authStore;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(_auth__WEBPACK_IMPORTED_MODULE_2__["default"], "authStore");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, _auth__WEBPACK_IMPORTED_MODULE_2__["default"], $$value => $$invalidate(3, $authStore = $$value));
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("NavBar", slots, []);
	let { dark = false } = $$props;
	let { is_hidden_mobile = false } = $$props;
	let { hasAuth = false } = $$props;
	const writable_props = ["dark", "is_hidden_mobile", "hasAuth"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<NavBar> was created with unknown prop '${key}'`);
	});

	const click_handler = () => window._Logout();

	$$self.$$set = $$props => {
		if ("dark" in $$props) $$invalidate(0, dark = $$props.dark);
		if ("is_hidden_mobile" in $$props) $$invalidate(1, is_hidden_mobile = $$props.is_hidden_mobile);
		if ("hasAuth" in $$props) $$invalidate(2, hasAuth = $$props.hasAuth);
	};

	$$self.$capture_state = () => ({
		settings: _settings__WEBPACK_IMPORTED_MODULE_1__["default"],
		authStore: _auth__WEBPACK_IMPORTED_MODULE_2__["default"],
		GitHubButton: _GitHubButton__WEBPACK_IMPORTED_MODULE_3__["default"],
		Icon: lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_4__["default"],
		Button: lluis_Button__WEBPACK_IMPORTED_MODULE_5__["default"],
		dark,
		is_hidden_mobile,
		hasAuth,
		$authStore
	});

	$$self.$inject_state = $$props => {
		if ("dark" in $$props) $$invalidate(0, dark = $$props.dark);
		if ("is_hidden_mobile" in $$props) $$invalidate(1, is_hidden_mobile = $$props.is_hidden_mobile);
		if ("hasAuth" in $$props) $$invalidate(2, hasAuth = $$props.hasAuth);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [dark, is_hidden_mobile, hasAuth, $authStore, click_handler];
}

class NavBar extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-17yvxfi-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { dark: 0, is_hidden_mobile: 1, hasAuth: 2 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "NavBar",
			options,
			id: create_fragment.name
		});
	}

	get dark() {
		throw new Error("<NavBar>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set dark(value) {
		throw new Error("<NavBar>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get is_hidden_mobile() {
		throw new Error("<NavBar>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set is_hidden_mobile(value) {
		throw new Error("<NavBar>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get hasAuth() {
		throw new Error("<NavBar>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set hasAuth(value) {
		throw new Error("<NavBar>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (NavBar);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vbGx1aXMvSWNvbi5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL2NvbXBvbmVudHMvR2l0SHViQnV0dG9uLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9OYXZCYXIuc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhHQVFnQixHQUFNLG1CQUFPLEdBQUksZ0JBQUksR0FBSSxRQUFLLE9BQU8sR0FBRyxPQUFPLEdBQUcsRUFBRTs7MEhBRDNDLEdBQUk7a0dBQXFCLEdBQUk7Ozs7Ozs7OzRGQUN0QyxHQUFNLG1CQUFPLEdBQUksZ0JBQUksR0FBSSxRQUFLLE9BQU8sR0FBRyxPQUFPLEdBQUcsRUFBRTs7OzswRkFEM0MsR0FBSTs7Ozs7bUdBQXFCLEdBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztPQU56QyxJQUFJLEdBQUcsUUFBUTtPQUNmLE1BQU0sR0FBRyxLQUFLO09BQ2QsSUFBSTtPQUNKLElBQUksR0FBRyxLQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ1FTO0FBQ0g7QUFDSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrRUFpQ1IsR0FBSzs7Ozs7Ozs7Ozs7a0dBQUwsR0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsySEFBTCxHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQUZ6QixHQUFLOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lCQUFMLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztlQTVDWSxPQUFPLENBQUMsSUFBSTtPQUMxQixJQUFJLFNBQVMsS0FBSyxDQUFDLGlEQUFpRDtTQUVsRSxnQkFBZ0IsV0FBVyxJQUFJLENBQUMsSUFBSTtVQUUxQyxnQkFBZ0I7Ozs7OztPQVNkLFFBQVEsR0FBRyxtQkFBTyxDQUFDLHdEQUFXO09BQ3pCLEtBQUssSUFBSSxLQUF3QixHQUFHLE1BQU0sQ0FBQyxLQUFLLEdBQUcsU0FBSSxLQUFLLEtBQUs7T0FDakUsSUFBSSxHQUFHLE9BQU87O0NBRXpCLHNEQUFPO01BQ0QsS0FBd0IsSUFBSSxNQUFNLENBQUMsU0FBUzttQkFDOUMsS0FBSyxHQUFHLEdBQUc7Ozs7RUFJYixRQUFRLENBQUMsS0FBSyxJQUFJLE1BQU0sRUFBRSxDQUFDLEdBQUcsRUFBRSxHQUFHLElBQUksSUFDckMsaURBQWlELEVBRWhELElBQUksQ0FBRSxHQUFHLElBQUssR0FBRyxDQUFDLElBQUksSUFDdEIsSUFBSSxJQUFJLGdCQUFnQjttQkFDdkIsS0FBSyxHQUFHLGdCQUFnQjs7T0FDcEIsSUFBd0I7SUFDMUIsTUFBTSxDQUFDLFVBQVUsR0FBRyxnQkFBZ0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDL0JWO0FBQ0g7QUFDVTtBQUNMO0FBQ0g7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3FCQXlCcEIsR0FBVSxJQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrQkFHVCxHQUFVLElBQUMsSUFBSSxDQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUZBQXBCLEdBQVUsSUFBQyxJQUFJLENBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzRCQUo1QixHQUFPLE9BQUksaURBQVEsQ0FBQyxRQUFRLENBQUMsV0FBVzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0hBZjFCLEdBQWdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzttQkFlOUIsR0FBTyxPQUFJLGlEQUFRLENBQUMsUUFBUSxDQUFDLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUhBZjFCLEdBQWdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztPQVI5QixJQUFJLEdBQUcsS0FBSztPQUNaLGdCQUFnQixHQUFHLEtBQUs7T0FDeEIsT0FBTyxHQUFHLEtBQUs7Ozs7Ozs7NkJBNEJHLE1BQU0sQ0FBQyxPQUFPIiwiZmlsZSI6ImFlYmU5ZjBmMmYxMDg2NWJmNGJkL2Fib3V0fmNvdXJzZV8kY291cnNlTmFtZX5jb3Vyc2VfJGNvdXJzZU5hbWUkOTNfc2tpbGxfJDkxaWR+ZGV2ZWxvcG1lbnR+ZGV2dG9vbHN+bGljZW5zZX5sb2dpbn5zaWduJDR+NjUwYmUxOGMuYWJvdXR+Y291cnNlXyRjb3Vyc2VOYW1lfmNvdXJzZV8kY291cnNlTmFtZSQ5M19za2lsbF8kOTFpZH5kZXZlbG9wbWVudH5kZXZ0b29sc35saWNlbnNlfmxvZ2lufnNpZ24kNH42NTBiZTE4Yy5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgc2l6ZSA9IFwibWVkaXVtXCJcbiAgZXhwb3J0IGxldCBwcmVmaXggPSBcImZhc1wiXG4gIGV4cG9ydCBsZXQgaWNvblxuICBleHBvcnQgbGV0IGxlZnQgPSBmYWxzZVxuPC9zY3JpcHQ+XG5cbjxzcGFuIGNsYXNzPVwie2BpY29uIGlzLSR7c2l6ZX1gfVwiIGNsYXNzOmlzLWxlZnQ9XCJ7bGVmdH1cIj5cbiAgPGkgY2xhc3M9XCJ7YCR7cHJlZml4fSBmYS0ke2ljb259ICR7c2l6ZSA9PT0gJ2xhcmdlJyA/ICdmYS0yeCcgOiAnJ31gfVwiPjwvaT5cbjwvc3Bhbj5cbiIsIjxzY3JpcHQgY29udGV4dD1cIm1vZHVsZVwiPlxuICBleHBvcnQgYXN5bmMgZnVuY3Rpb24gcHJlbG9hZChwYWdlKSB7XG4gICAgY29uc3QgcmVwbyA9IGF3YWl0IGZldGNoKFwiaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy9rYW50b3JkL0xpYnJlTGluZ29cIilcblxuICAgIGNvbnN0IHsgc3RhcmdhemVyc19jb3VudCB9ID0gYXdhaXQgcmVwby5qc29uKClcbiAgICByZXR1cm4ge1xuICAgICAgc3RhcmdhemVyc19jb3VudCxcbiAgICB9XG4gIH1cbjwvc2NyaXB0PlxuXG48c2NyaXB0PlxuICBpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSBcInN2ZWx0ZVwiXG4gIGltcG9ydCBJY29uIGZyb20gXCJsbHVpcy9JY29uXCJcbiAgaW1wb3J0IEJ1dHRvbiBmcm9tIFwibGx1aXMvQnV0dG9uXCJcbiAgY29uc3QgcE1lbW9pemUgPSByZXF1aXJlKFwicC1tZW1vaXplXCIpXG4gIGV4cG9ydCBsZXQgc3RhcnMgPSAocHJvY2Vzcy5icm93c2VyID09PSB0cnVlID8gd2luZG93LnN0YXJzIDogbnVsbCkgfHwgXCIgICBcIlxuICBleHBvcnQgbGV0IHNpemUgPSBcInNtYWxsXCJcblxuICBvbk1vdW50KGFzeW5jICgpID0+IHtcbiAgICBpZiAocHJvY2Vzcy5icm93c2VyID09PSB0cnVlICYmIHdpbmRvdy5pc0N5cHJlc3MpIHtcbiAgICAgIHN0YXJzID0gOTk5XG4gICAgICByZXR1cm5cbiAgICB9XG5cbiAgICBwTWVtb2l6ZShmZXRjaCwgeyBtYXhBZ2U6IDUgKiA2MCAqIDEwMDAgfSkoXG4gICAgICBcImh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vcmVwb3Mva2FudG9yZC9MaWJyZUxpbmdvXCJcbiAgICApXG4gICAgICAudGhlbigocmVzKSA9PiByZXMuanNvbigpKVxuICAgICAgLnRoZW4oKHsgc3RhcmdhemVyc19jb3VudCB9KSA9PiB7XG4gICAgICAgIHN0YXJzID0gc3RhcmdhemVyc19jb3VudFxuICAgICAgICBpZiAocHJvY2Vzcy5icm93c2VyID09PSB0cnVlKSB7XG4gICAgICAgICAgd2luZG93LnN0YXJfY291bnQgPSBzdGFyZ2F6ZXJzX2NvdW50XG4gICAgICAgIH1cbiAgICAgIH0pXG4gIH0pXG48L3NjcmlwdD5cblxuPEJ1dHRvblxuICB0YXJnZXQ9XCJfYmxhbmtcIlxuICBvdXRsaW5lZFxuICBpbnZlcnRlZFxuICBpbmZvXG4gIHtzaXplfVxuICBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL2thbnRvcmQvTGlicmVMaW5nb1wiPlxuICB7I2lmIHN0YXJzfVxuICAgIDxzcGFuIGNsYXNzPVwidGFnIGlzLXdoaXRlXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cInN0YXJzXCI+e3N0YXJzfTwvc3Bhbj5cbiAgICAgIDxzcGFuIGNsYXNzPVwiaWNvblwiPlxuICAgICAgICA8SWNvbiBpY29uPVwic3RhclwiIC8+XG4gICAgICA8L3NwYW4+XG4gICAgPC9zcGFuPlxuICB7L2lmfVxuICA8c3BhbiBjbGFzcz1cImlzLWhpZGRlbi1tb2JpbGVcIj5HaXRIdWI8L3NwYW4+XG48L0J1dHRvbj5cblxuPHN0eWxlPkBrZXlmcmFtZXMgc3BpbkFyb3VuZCB7XG4gIGZyb20ge1xuICAgIHRyYW5zZm9ybTogcm90YXRlKDBkZWcpOyB9XG4gIHRvIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgzNTlkZWcpOyB9IH1cblxuLnRhZyB7XG4gIGNvbG9yOiBpbmhlcml0ICFpbXBvcnRhbnQ7XG4gIHBhZGRpbmctbGVmdDogMDtcbiAgYmFja2dyb3VuZDogdHJhbnNwYXJlbnQgIWltcG9ydGFudDsgfVxuICAudGFnIC5zdGFycyB7XG4gICAgcGFkZGluZy10b3A6IDAuMWVtO1xuICAgIGZvbnQtZmFtaWx5OiBtb25vc3BhY2U7IH1cbiAgLnRhZyAuaWNvbiB7XG4gICAgbWFyZ2luLWxlZnQ6IDAgIWltcG9ydGFudDsgfVxuPC9zdHlsZT5cbiIsIjxzY3JpcHQ+XG4gIGltcG9ydCBzZXR0aW5ncyBmcm9tIFwiLi4vc2V0dGluZ3NcIlxuICBpbXBvcnQgYXV0aFN0b3JlIGZyb20gXCIuLi9hdXRoXCJcbiAgaW1wb3J0IEdpdEh1YkJ1dHRvbiBmcm9tIFwiLi9HaXRIdWJCdXR0b25cIlxuICBpbXBvcnQgSWNvbiBmcm9tIFwibGx1aXMvSWNvbi5zdmVsdGVcIlxuICBpbXBvcnQgQnV0dG9uIGZyb20gXCJsbHVpcy9CdXR0b25cIlxuICBleHBvcnQgbGV0IGRhcmsgPSBmYWxzZVxuICBleHBvcnQgbGV0IGlzX2hpZGRlbl9tb2JpbGUgPSBmYWxzZVxuICBleHBvcnQgbGV0IGhhc0F1dGggPSBmYWxzZVxuPC9zY3JpcHQ+XG5cbjxuYXZcbiAgY2xhc3M9XCJuYXZiYXJcIlxuICBjbGFzczpkYXJrXG4gIGNsYXNzOmlzLWhpZGRlbi1tb2JpbGU9XCJ7aXNfaGlkZGVuX21vYmlsZX1cIlxuICByb2xlPVwibmF2aWdhdGlvblwiXG4gIGFyaWEtbGFiZWw9XCJtYWluIG5hdmlnYXRpb25cIj5cbiAgPGRpdiBjbGFzcz1cIm5hdmJhci1icmFuZFwiPlxuICAgIDxhIGNsYXNzPVwibmF2YmFyLWl0ZW1cIiBocmVmPVwiL1wiPlxuICAgICAgPGltZyBzcmM9XCIvaW1hZ2VzL2xvZ28uc3ZnXCIgYWx0PVwiTGlicmVMaW5nb1wiIC8+XG4gICAgPC9hPlxuICA8L2Rpdj5cblxuICA8ZGl2IGNsYXNzPVwibmF2YmFyLXN0YXJ0XCI+PC9kaXY+XG5cbiAgPGRpdiBjbGFzcz1cIm5hdmJhci1lbmRcIj5cbiAgICA8ZGl2IGNsYXNzPVwibmF2YmFyLWl0ZW1cIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgICAgIDxHaXRIdWJCdXR0b24gLz5cbiAgICAgICAgeyNpZiBoYXNBdXRoICYmIHNldHRpbmdzLmZlYXR1cmVzLmF1dGhFbmFibGVkfVxuICAgICAgICAgIHsjaWYgJGF1dGhTdG9yZS51c2VyfVxuICAgICAgICAgICAgPEJ1dHRvbiBzaXplPVwic21hbGxcIiBvdXRsaW5lZCBpbnZlcnRlZCBpbmZvPlxuICAgICAgICAgICAgICA8SWNvbiBzaXplPVwic21hbGxcIiBpY29uPVwidXNlclwiIC8+XG4gICAgICAgICAgICAgIDxzcGFuPnskYXV0aFN0b3JlLnVzZXIubmFtZX08L3NwYW4+XG4gICAgICAgICAgICA8L0J1dHRvbj5cbiAgICAgICAgICAgIDxCdXR0b25cbiAgICAgICAgICAgICAgb246Y2xpY2s9XCJ7KCkgPT4gd2luZG93Ll9Mb2dvdXQoKX1cIlxuICAgICAgICAgICAgICBzaXplPVwic21hbGxcIlxuICAgICAgICAgICAgICBvdXRsaW5lZFxuICAgICAgICAgICAgICBpbnZlcnRlZFxuICAgICAgICAgICAgICBpbmZvPlxuICAgICAgICAgICAgICBMb2cgb3V0XG4gICAgICAgICAgICA8L0J1dHRvbj5cbiAgICAgICAgICB7OmVsc2V9XG4gICAgICAgICAgICA8QnV0dG9uIGhyZWY9XCIvc2lnbi11cFwiIHNpemU9XCJzbWFsbFwiIG91dGxpbmVkIGludmVydGVkIGluZm8+XG4gICAgICAgICAgICAgIFNpZ24gdXBcbiAgICAgICAgICAgIDwvQnV0dG9uPlxuICAgICAgICAgICAgPEJ1dHRvbiBocmVmPVwiL2xvZ2luXCIgc2l6ZT1cInNtYWxsXCIgb3V0bGluZWQgaW52ZXJ0ZWQgaW5mbz5cbiAgICAgICAgICAgICAgTG9nIGluXG4gICAgICAgICAgICA8L0J1dHRvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICB7L2lmfVxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9uYXY+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbi5uYXZiYXIuZGFyayB7XG4gIGJhY2tncm91bmQ6ICMzMjVmNzQ7XG4gIGNvbG9yOiAjYmZiNWFmOyB9XG5cbi5uYXZiYXIge1xuICBib3JkZXI6IDA7IH1cbiAgLm5hdmJhciAubmF2YmFyLWVuZCB7XG4gICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgIHJpZ2h0OiAwO1xuICAgIHRvcDogMDsgfVxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=