(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["course_$courseName~course_$courseName$93_skill_$91id~development~devtools~index"],{

/***/ "../lluis/Column.svelte":
/*!******************************!*\
  !*** ../lluis/Column.svelte ***!
  \******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Column.svelte generated by Svelte v3.25.0 */


const file = "home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Column.svelte";

function create_fragment(ctx) {
	let div;
	let current;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {
				"data-size": true,
				"data-size-desktop": true,
				"data-size-tablet": true,
				class: true
			});

			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			if (default_slot) default_slot.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size", /*size*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size-desktop", /*sizeDesktop*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size-tablet", /*sizeTablet*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "column");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third-desktop", /*sizeDesktop*/ ctx[1] === "1/3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-half-tablet", /*sizeTablet*/ ctx[2] === "1/2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third-tablet", /*sizeTablet*/ ctx[2] === "1/3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-quarter", /*size*/ ctx[0] === "1/4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third", /*size*/ ctx[0] === "1/3");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-three-fifths", /*size*/ ctx[0] === "3/5");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-1", /*size*/ ctx[0] === "1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 6, 0, 108);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);

			if (default_slot) {
				default_slot.m(div, null);
			}

			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			if (!current || dirty & /*size*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size", /*size*/ ctx[0]);
			}

			if (!current || dirty & /*sizeDesktop*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size-desktop", /*sizeDesktop*/ ctx[1]);
			}

			if (!current || dirty & /*sizeTablet*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "data-size-tablet", /*sizeTablet*/ ctx[2]);
			}

			if (dirty & /*sizeDesktop*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third-desktop", /*sizeDesktop*/ ctx[1] === "1/3");
			}

			if (dirty & /*sizeTablet*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-half-tablet", /*sizeTablet*/ ctx[2] === "1/2");
			}

			if (dirty & /*sizeTablet*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third-tablet", /*sizeTablet*/ ctx[2] === "1/3");
			}

			if (dirty & /*size*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-quarter", /*size*/ ctx[0] === "1/4");
			}

			if (dirty & /*size*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-one-third", /*size*/ ctx[0] === "1/3");
			}

			if (dirty & /*size*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-three-fifths", /*size*/ ctx[0] === "3/5");
			}

			if (dirty & /*size*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-1", /*size*/ ctx[0] === "1");
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (default_slot) default_slot.d(detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Column", slots, ['default']);
	let { size = null } = $$props;
	let { sizeDesktop = null } = $$props;
	let { sizeTablet = null } = $$props;
	const writable_props = ["size", "sizeDesktop", "sizeTablet"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Column> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("size" in $$props) $$invalidate(0, size = $$props.size);
		if ("sizeDesktop" in $$props) $$invalidate(1, sizeDesktop = $$props.sizeDesktop);
		if ("sizeTablet" in $$props) $$invalidate(2, sizeTablet = $$props.sizeTablet);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	$$self.$capture_state = () => ({ size, sizeDesktop, sizeTablet });

	$$self.$inject_state = $$props => {
		if ("size" in $$props) $$invalidate(0, size = $$props.size);
		if ("sizeDesktop" in $$props) $$invalidate(1, sizeDesktop = $$props.sizeDesktop);
		if ("sizeTablet" in $$props) $$invalidate(2, sizeTablet = $$props.sizeTablet);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [size, sizeDesktop, sizeTablet, $$scope, slots];
}

class Column extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { size: 0, sizeDesktop: 1, sizeTablet: 2 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Column",
			options,
			id: create_fragment.name
		});
	}

	get size() {
		throw new Error("<Column>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set size(value) {
		throw new Error("<Column>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get sizeDesktop() {
		throw new Error("<Column>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set sizeDesktop(value) {
		throw new Error("<Column>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get sizeTablet() {
		throw new Error("<Column>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set sizeTablet(value) {
		throw new Error("<Column>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Column);

/***/ }),

/***/ "../lluis/Columns.svelte":
/*!*******************************!*\
  !*** ../lluis/Columns.svelte ***!
  \*******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Columns.svelte generated by Svelte v3.25.0 */


const file = "home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Columns.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-15b2wn7-style";
	style.textContent = "@keyframes svelte-15b2wn7-spinAround{from{transform:rotate(0deg)}to{transform:rotate(359deg)}}@media screen and (max-width: 768px){.is-reversed.svelte-15b2wn7{flex-direction:column-reverse;display:flex}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQ29sdW1ucy5zdmVsdGUiLCJzb3VyY2VzIjpbIkNvbHVtbnMuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgbXVsdGlsaW5lID0gZmFsc2VcbiAgZXhwb3J0IGxldCByZXZlcnNlZCA9IGZhbHNlXG48L3NjcmlwdD5cblxuPGRpdlxuICBjbGFzcz1cImNvbHVtbnNcIlxuICBjbGFzczppcy1tdWx0aWxpbmU9XCJ7bXVsdGlsaW5lfVwiXG4gIGNsYXNzOmlzLXJldmVyc2VkPVwie3JldmVyc2VkfVwiPlxuICA8c2xvdCAvPlxuPC9kaXY+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbkBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gIC5pcy1yZXZlcnNlZCB7XG4gICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbi1yZXZlcnNlO1xuICAgIGRpc3BsYXk6IGZsZXg7IH0gfVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFZTyxXQUFXLHlCQUFXLENBQUMsQUFDNUIsSUFBSSxBQUFDLENBQUMsQUFDSixTQUFTLENBQUUsT0FBTyxJQUFJLENBQUMsQUFBRSxDQUFDLEFBQzVCLEVBQUUsQUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLEFBQUUsQ0FBQyxBQUFDLENBQUMsQUFFbEMsT0FBTyxNQUFNLENBQUMsR0FBRyxDQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUNwQyxZQUFZLGVBQUMsQ0FBQyxBQUNaLGNBQWMsQ0FBRSxjQUFjLENBQzlCLE9BQU8sQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUFDLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div;
	let current;
	const default_slot_template = /*#slots*/ ctx[3].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[2], null);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			if (default_slot) default_slot.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "columns svelte-15b2wn7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-multiline", /*multiline*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-reversed", /*reversed*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 5, 0, 81);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);

			if (default_slot) {
				default_slot.m(div, null);
			}

			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[2], dirty, null, null);
				}
			}

			if (dirty & /*multiline*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-multiline", /*multiline*/ ctx[0]);
			}

			if (dirty & /*reversed*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(div, "is-reversed", /*reversed*/ ctx[1]);
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (default_slot) default_slot.d(detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Columns", slots, ['default']);
	let { multiline = false } = $$props;
	let { reversed = false } = $$props;
	const writable_props = ["multiline", "reversed"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Columns> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("multiline" in $$props) $$invalidate(0, multiline = $$props.multiline);
		if ("reversed" in $$props) $$invalidate(1, reversed = $$props.reversed);
		if ("$$scope" in $$props) $$invalidate(2, $$scope = $$props.$$scope);
	};

	$$self.$capture_state = () => ({ multiline, reversed });

	$$self.$inject_state = $$props => {
		if ("multiline" in $$props) $$invalidate(0, multiline = $$props.multiline);
		if ("reversed" in $$props) $$invalidate(1, reversed = $$props.reversed);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [multiline, reversed, $$scope, slots];
}

class Columns extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-15b2wn7-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { multiline: 0, reversed: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Columns",
			options,
			id: create_fragment.name
		});
	}

	get multiline() {
		throw new Error("<Columns>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set multiline(value) {
		throw new Error("<Columns>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get reversed() {
		throw new Error("<Columns>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set reversed(value) {
		throw new Error("<Columns>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Columns);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vbGx1aXMvQ29sdW1uLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi4vbGx1aXMvQ29sdW1ucy5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrRkFPYyxHQUFJOzhHQUNJLEdBQVc7NEdBQ1osR0FBVTs7cUhBQ0EsR0FBVyxRQUFLLEtBQUs7OEdBQzNCLEdBQVUsUUFBSyxLQUFLO21IQUNmLEdBQVUsUUFBSyxLQUFLO3dHQUN6QixHQUFJLFFBQUssS0FBSztzR0FDaEIsR0FBSSxRQUFLLEtBQUs7eUdBQ1gsR0FBSSxRQUFLLEtBQUs7OEZBQ3pCLEdBQUksUUFBSyxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnR0FUYixHQUFJOzs7OytHQUNJLEdBQVc7Ozs7NkdBQ1osR0FBVTs7OztzSEFDQSxHQUFXLFFBQUssS0FBSzs7OzsrR0FDM0IsR0FBVSxRQUFLLEtBQUs7Ozs7b0hBQ2YsR0FBVSxRQUFLLEtBQUs7Ozs7eUdBQ3pCLEdBQUksUUFBSyxLQUFLOzs7O3VHQUNoQixHQUFJLFFBQUssS0FBSzs7OzswR0FDWCxHQUFJLFFBQUssS0FBSzs7OzsrRkFDekIsR0FBSSxRQUFLLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BZmQsSUFBSSxHQUFHLElBQUk7T0FDWCxXQUFXLEdBQUcsSUFBSTtPQUNsQixVQUFVLEdBQUcsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzJHQ0lQLEdBQVM7eUdBQ1YsR0FBUTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NEdBRFAsR0FBUzs7OzswR0FDVixHQUFROzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztPQVBqQixTQUFTLEdBQUcsS0FBSztPQUNqQixRQUFRLEdBQUcsS0FBSyIsImZpbGUiOiJhZWJlOWYwZjJmMTA4NjViZjRiZC9jb3Vyc2VfJGNvdXJzZU5hbWV+Y291cnNlXyRjb3Vyc2VOYW1lJDkzX3NraWxsXyQ5MWlkfmRldmVsb3BtZW50fmRldnRvb2xzfmluZGV4LmNvdXJzZV8kY291cnNlTmFtZX5jb3Vyc2VfJGNvdXJzZU5hbWUkOTNfc2tpbGxfJDkxaWR+ZGV2ZWxvcG1lbnR+ZGV2dG9vbHN+aW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBleHBvcnQgbGV0IHNpemUgPSBudWxsXG4gIGV4cG9ydCBsZXQgc2l6ZURlc2t0b3AgPSBudWxsXG4gIGV4cG9ydCBsZXQgc2l6ZVRhYmxldCA9IG51bGxcbjwvc2NyaXB0PlxuXG48ZGl2XG4gIGRhdGEtc2l6ZT1cIntzaXplfVwiXG4gIGRhdGEtc2l6ZS1kZXNrdG9wPVwie3NpemVEZXNrdG9wfVwiXG4gIGRhdGEtc2l6ZS10YWJsZXQ9XCJ7c2l6ZVRhYmxldH1cIlxuICBjbGFzczppcy1vbmUtdGhpcmQtZGVza3RvcD1cIntzaXplRGVza3RvcCA9PT0gJzEvMyd9XCJcbiAgY2xhc3M6aXMtaGFsZi10YWJsZXQ9XCJ7c2l6ZVRhYmxldCA9PT0gJzEvMid9XCJcbiAgY2xhc3M6aXMtb25lLXRoaXJkLXRhYmxldD1cIntzaXplVGFibGV0ID09PSAnMS8zJ31cIlxuICBjbGFzczppcy1vbmUtcXVhcnRlcj1cIntzaXplID09PSAnMS80J31cIlxuICBjbGFzczppcy1vbmUtdGhpcmQ9XCJ7c2l6ZSA9PT0gJzEvMyd9XCJcbiAgY2xhc3M6aXMtdGhyZWUtZmlmdGhzPVwie3NpemUgPT09ICczLzUnfVwiXG4gIGNsYXNzOmlzLTE9XCJ7c2l6ZSA9PT0gJzEnfVwiXG4gIGNsYXNzPVwiY29sdW1uXCI+XG4gIDxzbG90IC8+XG48L2Rpdj5cbiIsIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgbXVsdGlsaW5lID0gZmFsc2VcbiAgZXhwb3J0IGxldCByZXZlcnNlZCA9IGZhbHNlXG48L3NjcmlwdD5cblxuPGRpdlxuICBjbGFzcz1cImNvbHVtbnNcIlxuICBjbGFzczppcy1tdWx0aWxpbmU9XCJ7bXVsdGlsaW5lfVwiXG4gIGNsYXNzOmlzLXJldmVyc2VkPVwie3JldmVyc2VkfVwiPlxuICA8c2xvdCAvPlxuPC9kaXY+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbkBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gIC5pcy1yZXZlcnNlZCB7XG4gICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbi1yZXZlcnNlO1xuICAgIGRpc3BsYXk6IGZsZXg7IH0gfVxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=