(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "../lluis/Box.svelte":
/*!***************************!*\
  !*** ../lluis/Box.svelte ***!
  \***************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Box.svelte generated by Svelte v3.25.0 */


const file = "home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/Box.svelte";

function create_fragment(ctx) {
	let div;
	let current;
	const default_slot_template = /*#slots*/ ctx[1].default;
	const default_slot = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_slot"])(default_slot_template, ctx, /*$$scope*/ ctx[0], null);

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (default_slot) default_slot.c();
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			if (default_slot) default_slot.l(div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "box");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 0, 0, 0);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);

			if (default_slot) {
				default_slot.m(div, null);
			}

			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 1) {
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["update_slot"])(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[0], dirty, null, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(default_slot, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(default_slot, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (default_slot) default_slot.d(detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Box", slots, ['default']);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Box> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("$$scope" in $$props) $$invalidate(0, $$scope = $$props.$$scope);
	};

	return [$$scope, slots];
}

class Box extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Box",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Box);

/***/ }),

/***/ "./src/components/LicenseLogo.svelte":
/*!*******************************************!*\
  !*** ./src/components/LicenseLogo.svelte ***!
  \*******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/LicenseLogo.svelte generated by Svelte v3.25.0 */


const file = "src/components/LicenseLogo.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1hagzfr-style";
	style.textContent = "img.svelte-1hagzfr{height:2.5em;mix-blend-mode:multiply;opacity:0.5}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTGljZW5zZUxvZ28uc3ZlbHRlIiwic291cmNlcyI6WyJMaWNlbnNlTG9nby5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPGltZ1xuICBzcmM9XCJpbWFnZXMvYWdwbC1sb2dvLnN2Z1wiXG4gIGFsdD1cIkxpY2Vuc2VkIHVuZGVyIEFHUEwgLSBGcmVlIGFzIGluIEZyZWVkb21cIiAvPlxuXG48c3R5bGU+aW1nIHtcbiAgaGVpZ2h0OiAyLjVlbTtcbiAgbWl4LWJsZW5kLW1vZGU6IG11bHRpcGx5O1xuICBvcGFjaXR5OiAwLjU7IH1cbjwvc3R5bGU+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBSU8sR0FBRyxlQUFDLENBQUMsQUFDVixNQUFNLENBQUUsS0FBSyxDQUNiLGNBQWMsQ0FBRSxRQUFRLENBQ3hCLE9BQU8sQ0FBRSxHQUFHLEFBQUUsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let img;
	let img_src_value;

	const block = {
		c: function create() {
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h();
		},
		l: function claim(nodes) {
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "IMG", { src: true, alt: true, class: true });
			this.h();
		},
		h: function hydrate() {
			if (img.src !== (img_src_value = "images/agpl-logo.svg")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "src", img_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "alt", "Licensed under AGPL - Free as in Freedom");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "class", "svelte-1hagzfr");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 0, 0, 0);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, img, anchor);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(img);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("LicenseLogo", slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<LicenseLogo> was created with unknown prop '${key}'`);
	});

	return [];
}

class LicenseLogo extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1hagzfr-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "LicenseLogo",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (LicenseLogo);

/***/ }),

/***/ "./src/components/Mascot.svelte":
/*!**************************************!*\
  !*** ./src/components/Mascot.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Mascot.svelte generated by Svelte v3.25.0 */


const file = "src/components/Mascot.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1ceej21-style";
	style.textContent = ".glow.svelte-1ceej21{filter:drop-shadow(0 0 2em #ffffff1c)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTWFzY290LnN2ZWx0ZSIsInNvdXJjZXMiOlsiTWFzY290LnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBleHBvcnQgbGV0IHNoYWRvdyA9IHRydWVcbiAgZXhwb3J0IGxldCBnbG93ID0gZmFsc2VcbiAgbGV0IGltYWdlVVJMID1cbiAgICBzaGFkb3cgPT09IHRydWVcbiAgICAgID8gXCJpbWFnZXMvbWFzY290LWpldHBhY2suc3ZnXCJcbiAgICAgIDogXCJpbWFnZXMvbWFzY290LWpldHBhY2stbm9zaGFkb3cuc3ZnXCJcbjwvc2NyaXB0PlxuXG48aW1nIGRhdGEtdGVzdD1cIm1hc2NvdC1qZXRwYWNrXCIgc3JjPVwie2ltYWdlVVJMfVwiIGFsdD1cIlwiIGNsYXNzOmdsb3cgLz5cblxuPHN0eWxlPi5nbG93IHtcbiAgZmlsdGVyOiBkcm9wLXNoYWRvdygwIDAgMmVtICNmZmZmZmYxYyk7IH1cbjwvc3R5bGU+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBV08sS0FBSyxlQUFDLENBQUMsQUFDWixNQUFNLENBQUUsWUFBWSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxTQUFTLENBQUMsQUFBRSxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let img;
	let img_src_value;

	const block = {
		c: function create() {
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h();
		},
		l: function claim(nodes) {
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "IMG", {
				"data-test": true,
				src: true,
				alt: true,
				class: true
			});

			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "data-test", "mascot-jetpack");
			if (img.src !== (img_src_value = /*imageURL*/ ctx[1])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "src", img_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "alt", "");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "class", "svelte-1ceej21");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(img, "glow", /*glow*/ ctx[0]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 9, 0, 191);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, img, anchor);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*glow*/ 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(img, "glow", /*glow*/ ctx[0]);
			}
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(img);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Mascot", slots, []);
	let { shadow = true } = $$props;
	let { glow = false } = $$props;

	let imageURL = shadow === true
	? "images/mascot-jetpack.svg"
	: "images/mascot-jetpack-noshadow.svg";

	const writable_props = ["shadow", "glow"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Mascot> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ("shadow" in $$props) $$invalidate(2, shadow = $$props.shadow);
		if ("glow" in $$props) $$invalidate(0, glow = $$props.glow);
	};

	$$self.$capture_state = () => ({ shadow, glow, imageURL });

	$$self.$inject_state = $$props => {
		if ("shadow" in $$props) $$invalidate(2, shadow = $$props.shadow);
		if ("glow" in $$props) $$invalidate(0, glow = $$props.glow);
		if ("imageURL" in $$props) $$invalidate(1, imageURL = $$props.imageURL);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [glow, imageURL, shadow];
}

class Mascot extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1ceej21-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { shadow: 2, glow: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Mascot",
			options,
			id: create_fragment.name
		});
	}

	get shadow() {
		throw new Error("<Mascot>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set shadow(value) {
		throw new Error("<Mascot>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get glow() {
		throw new Error("<Mascot>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set glow(value) {
		throw new Error("<Mascot>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Mascot);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_Mascot__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/Mascot */ "./src/components/Mascot.svelte");
/* harmony import */ var _components_LicenseLogo__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/LicenseLogo */ "./src/components/LicenseLogo.svelte");
/* harmony import */ var lluis_Button__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! lluis/Button */ "../lluis/Button.svelte");
/* harmony import */ var lluis_Box__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! lluis/Box */ "../lluis/Box.svelte");
/* harmony import */ var lluis_Column__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! lluis/Column */ "../lluis/Column.svelte");
/* harmony import */ var lluis_Columns__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! lluis/Columns */ "../lluis/Columns.svelte");
/* harmony import */ var svelte_i18n__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! svelte-i18n */ "./node_modules/svelte-i18n/dist/runtime.esm.js");
/* src/routes/index.svelte generated by Svelte v3.25.0 */









const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-38z88o-style";
	style.textContent = "@keyframes svelte-38z88o-spinAround{from{transform:rotate(0deg)}to{transform:rotate(359deg)}}.hero.svelte-38z88o{background-color:#325f74}.license.svelte-38z88o{position:absolute;right:1em;bottom:1em}@media screen and (max-width: 768px){.mascot.svelte-38z88o{width:45%;margin:auto;margin-top:-3em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IE1hc2NvdCBmcm9tIFwiLi4vY29tcG9uZW50cy9NYXNjb3RcIlxuICBpbXBvcnQgTGljZW5zZUxvZ28gZnJvbSBcIi4uL2NvbXBvbmVudHMvTGljZW5zZUxvZ29cIlxuICBpbXBvcnQgQnV0dG9uIGZyb20gXCJsbHVpcy9CdXR0b25cIlxuICBpbXBvcnQgQm94IGZyb20gXCJsbHVpcy9Cb3hcIlxuICBpbXBvcnQgQ29sdW1uIGZyb20gXCJsbHVpcy9Db2x1bW5cIlxuICBpbXBvcnQgQ29sdW1ucyBmcm9tIFwibGx1aXMvQ29sdW1uc1wiXG4gIGltcG9ydCB7IF8gfSBmcm9tIFwic3ZlbHRlLWkxOG5cIlxuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPnskXygnbWV0YS50aXRsZScpfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2VjdGlvbiBjbGFzcz1cImhlcm8gaXMtYm9sZCBpcy1mdWxsaGVpZ2h0XCI+XG4gIDxkaXYgY2xhc3M9XCJoZXJvLWJvZHlcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgICA8Q29sdW1ucz5cbiAgICAgICAgPENvbHVtbiBzaXplPVwiMS80XCI+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cIm1hc2NvdFwiPlxuICAgICAgICAgICAgPE1hc2NvdCBzaGFkb3c9XCJ7ZmFsc2V9XCIgZ2xvdz1cInt0cnVlfVwiIC8+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvQ29sdW1uPlxuICAgICAgICA8Q29sdW1uPlxuICAgICAgICAgIDxCb3g+XG4gICAgICAgICAgICA8aDEgY2xhc3M9XCJ0aXRsZVwiPkxpYnJlTGluZ288L2gxPlxuICAgICAgICAgICAgPGgyIGNsYXNzPVwic3VidGl0bGVcIj57JF8oJ2luZGV4LnN1YnRpdGxlJyl9PC9oMj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgICAgICAgICAgIDxCdXR0b24gcHJpbWFyeSBocmVmPVwiY291cnNlL3NwYW5pc2gtZnJvbS1lbmdsaXNoXCI+XG4gICAgICAgICAgICAgICAgeyRfKCdpbmRleC5zdGFydF9zcGFuaXNoX2NvdXJzZScpfVxuICAgICAgICAgICAgICA8L0J1dHRvbj5cblxuICAgICAgICAgICAgICA8QnV0dG9uIHByaW1hcnkgaGlkZGVuIGhyZWY9XCJjb3Vyc2UvZ2VybWFuLWZyb20tZW5nbGlzaFwiPlxuICAgICAgICAgICAgICAgIHskXygnaW5kZXguc3RhcnRfZ2VybWFuX2NvdXJzZScpfVxuICAgICAgICAgICAgICA8L0J1dHRvbj5cblxuICAgICAgICAgICAgICA8QnV0dG9uIHByaW1hcnkgaHJlZj1cImFib3V0XCI+XG4gICAgICAgICAgICAgICAgeyRfKCdpbmRleC5hYm91dF9saWJyZWxpbmdvJyl9XG4gICAgICAgICAgICAgIDwvQnV0dG9uPlxuXG4gICAgICAgICAgICAgIDxCdXR0b24gcHJpbWFyeSBocmVmPVwiZGV2ZWxvcG1lbnRcIj5EZXZlbG9wbWVudCBwcm9ncmVzczwvQnV0dG9uPlxuICAgICAgICAgICAgICA8YSBocmVmPVwiL2RldnRvb2xzXCIgY2xhc3M9XCJpcy1pbnZpc2libGVcIj48L2E+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L0JveD5cbiAgICAgICAgPC9Db2x1bW4+XG4gICAgICA8L0NvbHVtbnM+XG4gICAgPC9kaXY+XG5cbiAgPC9kaXY+XG48L3NlY3Rpb24+XG5cbjxkaXYgY2xhc3M9XCJsaWNlbnNlXCI+XG4gIDxMaWNlbnNlTG9nbyAvPlxuPC9kaXY+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbi50aXRsZSBpbWcge1xuICBoZWlnaHQ6IDNlbTsgfVxuXG4uaGVybyB7XG4gIGJhY2tncm91bmQtY29sb3I6ICMzMjVmNzQ7IH1cblxuLmxpY2Vuc2Uge1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHJpZ2h0OiAxZW07XG4gIGJvdHRvbTogMWVtOyB9XG5cbkBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gIC5tYXNjb3Qge1xuICAgIHdpZHRoOiA0NSU7XG4gICAgbWFyZ2luOiBhdXRvO1xuICAgIG1hcmdpbi10b3A6IC0zZW07IH0gfVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUF1RE8sV0FBVyx3QkFBVyxDQUFDLEFBQzVCLElBQUksQUFBQyxDQUFDLEFBQ0osU0FBUyxDQUFFLE9BQU8sSUFBSSxDQUFDLEFBQUUsQ0FBQyxBQUM1QixFQUFFLEFBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxPQUFPLE1BQU0sQ0FBQyxBQUFFLENBQUMsQUFBQyxDQUFDLEFBS2xDLEtBQUssY0FBQyxDQUFDLEFBQ0wsZ0JBQWdCLENBQUUsT0FBTyxBQUFFLENBQUMsQUFFOUIsUUFBUSxjQUFDLENBQUMsQUFDUixRQUFRLENBQUUsUUFBUSxDQUNsQixLQUFLLENBQUUsR0FBRyxDQUNWLE1BQU0sQ0FBRSxHQUFHLEFBQUUsQ0FBQyxBQUVoQixPQUFPLE1BQU0sQ0FBQyxHQUFHLENBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3BDLE9BQU8sY0FBQyxDQUFDLEFBQ1AsS0FBSyxDQUFFLEdBQUcsQ0FDVixNQUFNLENBQUUsSUFBSSxDQUNaLFVBQVUsQ0FBRSxJQUFJLEFBQUUsQ0FBQyxBQUFDLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

// (19:8) <Column size="1/4">
function create_default_slot_7(ctx) {
	let div;
	let mascot;
	let current;

	mascot = new _components_Mascot__WEBPACK_IMPORTED_MODULE_1__["default"]({
			props: { shadow: false, glow: true },
			$$inline: true
		});

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(mascot.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(mascot.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "mascot svelte-38z88o");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 19, 10, 511);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(mascot, div, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(mascot.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(mascot.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(mascot);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_7.name,
		type: "slot",
		source: "(19:8) <Column size=\\\"1/4\\\">",
		ctx
	});

	return block;
}

// (29:14) <Button primary href="course/spanish-from-english">
function create_default_slot_6(ctx) {
	let t_value = /*$_*/ ctx[0]("index.start_spanish_course") + "";
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, t_value);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$_*/ 1 && t_value !== (t_value = /*$_*/ ctx[0]("index.start_spanish_course") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_6.name,
		type: "slot",
		source: "(29:14) <Button primary href=\\\"course/spanish-from-english\\\">",
		ctx
	});

	return block;
}

// (33:14) <Button primary hidden href="course/german-from-english">
function create_default_slot_5(ctx) {
	let t_value = /*$_*/ ctx[0]("index.start_german_course") + "";
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, t_value);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$_*/ 1 && t_value !== (t_value = /*$_*/ ctx[0]("index.start_german_course") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_5.name,
		type: "slot",
		source: "(33:14) <Button primary hidden href=\\\"course/german-from-english\\\">",
		ctx
	});

	return block;
}

// (37:14) <Button primary href="about">
function create_default_slot_4(ctx) {
	let t_value = /*$_*/ ctx[0]("index.about_librelingo") + "";
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, t_value);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*$_*/ 1 && t_value !== (t_value = /*$_*/ ctx[0]("index.about_librelingo") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_4.name,
		type: "slot",
		source: "(37:14) <Button primary href=\\\"about\\\">",
		ctx
	});

	return block;
}

// (41:14) <Button primary href="development">
function create_default_slot_3(ctx) {
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Development progress");
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "Development progress");
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_3.name,
		type: "slot",
		source: "(41:14) <Button primary href=\\\"development\\\">",
		ctx
	});

	return block;
}

// (25:10) <Box>
function create_default_slot_2(ctx) {
	let h1;
	let t0;
	let t1;
	let h2;
	let t2_value = /*$_*/ ctx[0]("index.subtitle") + "";
	let t2;
	let t3;
	let div;
	let button0;
	let t4;
	let button1;
	let t5;
	let button2;
	let t6;
	let button3;
	let t7;
	let a;
	let current;

	button0 = new lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				primary: true,
				href: "course/spanish-from-english",
				$$slots: { default: [create_default_slot_6] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button1 = new lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				primary: true,
				hidden: true,
				href: "course/german-from-english",
				$$slots: { default: [create_default_slot_5] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button2 = new lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				primary: true,
				href: "about",
				$$slots: { default: [create_default_slot_4] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button3 = new lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				primary: true,
				href: "development",
				$$slots: { default: [create_default_slot_3] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("LibreLingo");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t2_value);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button0.$$.fragment);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button1.$$.fragment);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button2.$$.fragment);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button3.$$.fragment);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			this.h();
		},
		l: function claim(nodes) {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "LibreLingo");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, t2_value);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button0.$$.fragment, div_nodes);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button1.$$.fragment, div_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button2.$$.fragment, div_nodes);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button3.$$.fragment, div_nodes);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div_nodes);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div_nodes, "A", { href: true, class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "title");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 25, 12, 666);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "subtitle");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 26, 12, 712);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "/devtools");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "is-invisible");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 41, 14, 1293);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "buttons");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 27, 12, 773);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, h1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, h2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button0, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button1, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button2, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button3, div, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, a);
			current = true;
		},
		p: function update(ctx, dirty) {
			if ((!current || dirty & /*$_*/ 1) && t2_value !== (t2_value = /*$_*/ ctx[0]("index.subtitle") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t2, t2_value);
			const button0_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				button0_changes.$$scope = { dirty, ctx };
			}

			button0.$set(button0_changes);
			const button1_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				button1_changes.$$scope = { dirty, ctx };
			}

			button1.$set(button1_changes);
			const button2_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				button2_changes.$$scope = { dirty, ctx };
			}

			button2.$set(button2_changes);
			const button3_changes = {};

			if (dirty & /*$$scope*/ 2) {
				button3_changes.$$scope = { dirty, ctx };
			}

			button3.$set(button3_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button2.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button3.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button2.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button3.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(h1);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(h2);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t3);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button3);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_2.name,
		type: "slot",
		source: "(25:10) <Box>",
		ctx
	});

	return block;
}

// (24:8) <Column>
function create_default_slot_1(ctx) {
	let box;
	let current;

	box = new lluis_Box__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				$$slots: { default: [create_default_slot_2] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(box.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(box.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(box, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const box_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				box_changes.$$scope = { dirty, ctx };
			}

			box.$set(box_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(box.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(box.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(box, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot_1.name,
		type: "slot",
		source: "(24:8) <Column>",
		ctx
	});

	return block;
}

// (18:6) <Columns>
function create_default_slot(ctx) {
	let column0;
	let t;
	let column1;
	let current;

	column0 = new lluis_Column__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				size: "1/4",
				$$slots: { default: [create_default_slot_7] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	column1 = new lluis_Column__WEBPACK_IMPORTED_MODULE_5__["default"]({
			props: {
				$$slots: { default: [create_default_slot_1] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(column0.$$.fragment);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(column1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(column0.$$.fragment, nodes);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(column1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(column0, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(column1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const column0_changes = {};

			if (dirty & /*$$scope*/ 2) {
				column0_changes.$$scope = { dirty, ctx };
			}

			column0.$set(column0_changes);
			const column1_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				column1_changes.$$scope = { dirty, ctx };
			}

			column1.$set(column1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(column0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(column1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(column0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(column1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(column0, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(column1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(18:6) <Columns>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let title_value;
	let t0;
	let section;
	let div1;
	let div0;
	let columns;
	let t1;
	let div2;
	let licenselogo;
	let current;
	document.title = title_value = /*$_*/ ctx[0]("meta.title");

	columns = new lluis_Columns__WEBPACK_IMPORTED_MODULE_6__["default"]({
			props: {
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	licenselogo = new _components_LicenseLogo__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(columns.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(licenselogo.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-f92ebs\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(columns.$$.fragment, div0_nodes);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(licenselogo.$$.fragment, div2_nodes);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 16, 4, 433);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "hero-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 15, 2, 405);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "hero is-bold is-fullheight svelte-38z88o");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 14, 0, 358);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "license svelte-38z88o");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 51, 0, 1443);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(columns, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(licenselogo, div2, null);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			if ((!current || dirty & /*$_*/ 1) && title_value !== (title_value = /*$_*/ ctx[0]("meta.title"))) {
				document.title = title_value;
			}

			const columns_changes = {};

			if (dirty & /*$$scope, $_*/ 3) {
				columns_changes.$$scope = { dirty, ctx };
			}

			columns.$set(columns_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(columns.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(licenselogo.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(columns.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(licenselogo.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(columns);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(licenselogo);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let $_;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_store"])(svelte_i18n__WEBPACK_IMPORTED_MODULE_7__["_"], "_");
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["component_subscribe"])($$self, svelte_i18n__WEBPACK_IMPORTED_MODULE_7__["_"], $$value => $$invalidate(0, $_ = $$value));
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({
		Mascot: _components_Mascot__WEBPACK_IMPORTED_MODULE_1__["default"],
		LicenseLogo: _components_LicenseLogo__WEBPACK_IMPORTED_MODULE_2__["default"],
		Button: lluis_Button__WEBPACK_IMPORTED_MODULE_3__["default"],
		Box: lluis_Box__WEBPACK_IMPORTED_MODULE_4__["default"],
		Column: lluis_Column__WEBPACK_IMPORTED_MODULE_5__["default"],
		Columns: lluis_Columns__WEBPACK_IMPORTED_MODULE_6__["default"],
		_: svelte_i18n__WEBPACK_IMPORTED_MODULE_7__["_"],
		$_
	});

	return [$_];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-38z88o-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9NYXNjb3Quc3ZlbHRlIiwid2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7aURBU3NDLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BUmpDLE1BQU0sR0FBRyxJQUFJO09BQ2IsSUFBSSxHQUFHLEtBQUs7O0tBQ25CLFFBQVEsR0FDVixNQUFNLEtBQUssSUFBSTtHQUNYLDJCQUEyQjtHQUMzQixvQ0FBb0M7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDTEQ7QUFDVTtBQUNsQjtBQUNOO0FBQ007QUFDRTtBQUNKOzs7Ozs7Ozs7Ozs7Ozs7OztvQkFhSixLQUFLLFFBQVUsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztzQkFTL0IsR0FBRSxJQUFDLDRCQUE0Qjs7Ozs7Ozs7Ozs7Ozs7eURBQS9CLEdBQUUsSUFBQyw0QkFBNEI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NCQUkvQixHQUFFLElBQUMsMkJBQTJCOzs7Ozs7Ozs7Ozs7Ozt5REFBOUIsR0FBRSxJQUFDLDJCQUEyQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0JBSTlCLEdBQUUsSUFBQyx3QkFBd0I7Ozs7Ozs7Ozs7Ozs7O3lEQUEzQixHQUFFLElBQUMsd0JBQXdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUJBWFYsR0FBRSxJQUFDLGdCQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUFBbkIsR0FBRSxJQUFDLGdCQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7dUNBZjNDLEdBQUUsSUFBQyxZQUFZOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytFQUFmLEdBQUUsSUFBQyxZQUFZIiwiZmlsZSI6ImFlYmU5ZjBmMmYxMDg2NWJmNGJkL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgZXhwb3J0IGxldCBzaGFkb3cgPSB0cnVlXG4gIGV4cG9ydCBsZXQgZ2xvdyA9IGZhbHNlXG4gIGxldCBpbWFnZVVSTCA9XG4gICAgc2hhZG93ID09PSB0cnVlXG4gICAgICA/IFwiaW1hZ2VzL21hc2NvdC1qZXRwYWNrLnN2Z1wiXG4gICAgICA6IFwiaW1hZ2VzL21hc2NvdC1qZXRwYWNrLW5vc2hhZG93LnN2Z1wiXG48L3NjcmlwdD5cblxuPGltZyBkYXRhLXRlc3Q9XCJtYXNjb3QtamV0cGFja1wiIHNyYz1cIntpbWFnZVVSTH1cIiBhbHQ9XCJcIiBjbGFzczpnbG93IC8+XG5cbjxzdHlsZT4uZ2xvdyB7XG4gIGZpbHRlcjogZHJvcC1zaGFkb3coMCAwIDJlbSAjZmZmZmZmMWMpOyB9XG48L3N0eWxlPlxuIiwiPHNjcmlwdD5cbiAgaW1wb3J0IE1hc2NvdCBmcm9tIFwiLi4vY29tcG9uZW50cy9NYXNjb3RcIlxuICBpbXBvcnQgTGljZW5zZUxvZ28gZnJvbSBcIi4uL2NvbXBvbmVudHMvTGljZW5zZUxvZ29cIlxuICBpbXBvcnQgQnV0dG9uIGZyb20gXCJsbHVpcy9CdXR0b25cIlxuICBpbXBvcnQgQm94IGZyb20gXCJsbHVpcy9Cb3hcIlxuICBpbXBvcnQgQ29sdW1uIGZyb20gXCJsbHVpcy9Db2x1bW5cIlxuICBpbXBvcnQgQ29sdW1ucyBmcm9tIFwibGx1aXMvQ29sdW1uc1wiXG4gIGltcG9ydCB7IF8gfSBmcm9tIFwic3ZlbHRlLWkxOG5cIlxuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPnskXygnbWV0YS50aXRsZScpfTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2VjdGlvbiBjbGFzcz1cImhlcm8gaXMtYm9sZCBpcy1mdWxsaGVpZ2h0XCI+XG4gIDxkaXYgY2xhc3M9XCJoZXJvLWJvZHlcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgICA8Q29sdW1ucz5cbiAgICAgICAgPENvbHVtbiBzaXplPVwiMS80XCI+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cIm1hc2NvdFwiPlxuICAgICAgICAgICAgPE1hc2NvdCBzaGFkb3c9XCJ7ZmFsc2V9XCIgZ2xvdz1cInt0cnVlfVwiIC8+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvQ29sdW1uPlxuICAgICAgICA8Q29sdW1uPlxuICAgICAgICAgIDxCb3g+XG4gICAgICAgICAgICA8aDEgY2xhc3M9XCJ0aXRsZVwiPkxpYnJlTGluZ288L2gxPlxuICAgICAgICAgICAgPGgyIGNsYXNzPVwic3VidGl0bGVcIj57JF8oJ2luZGV4LnN1YnRpdGxlJyl9PC9oMj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJidXR0b25zXCI+XG4gICAgICAgICAgICAgIDxCdXR0b24gcHJpbWFyeSBocmVmPVwiY291cnNlL3NwYW5pc2gtZnJvbS1lbmdsaXNoXCI+XG4gICAgICAgICAgICAgICAgeyRfKCdpbmRleC5zdGFydF9zcGFuaXNoX2NvdXJzZScpfVxuICAgICAgICAgICAgICA8L0J1dHRvbj5cblxuICAgICAgICAgICAgICA8QnV0dG9uIHByaW1hcnkgaGlkZGVuIGhyZWY9XCJjb3Vyc2UvZ2VybWFuLWZyb20tZW5nbGlzaFwiPlxuICAgICAgICAgICAgICAgIHskXygnaW5kZXguc3RhcnRfZ2VybWFuX2NvdXJzZScpfVxuICAgICAgICAgICAgICA8L0J1dHRvbj5cblxuICAgICAgICAgICAgICA8QnV0dG9uIHByaW1hcnkgaHJlZj1cImFib3V0XCI+XG4gICAgICAgICAgICAgICAgeyRfKCdpbmRleC5hYm91dF9saWJyZWxpbmdvJyl9XG4gICAgICAgICAgICAgIDwvQnV0dG9uPlxuXG4gICAgICAgICAgICAgIDxCdXR0b24gcHJpbWFyeSBocmVmPVwiZGV2ZWxvcG1lbnRcIj5EZXZlbG9wbWVudCBwcm9ncmVzczwvQnV0dG9uPlxuICAgICAgICAgICAgICA8YSBocmVmPVwiL2RldnRvb2xzXCIgY2xhc3M9XCJpcy1pbnZpc2libGVcIj48L2E+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L0JveD5cbiAgICAgICAgPC9Db2x1bW4+XG4gICAgICA8L0NvbHVtbnM+XG4gICAgPC9kaXY+XG5cbiAgPC9kaXY+XG48L3NlY3Rpb24+XG5cbjxkaXYgY2xhc3M9XCJsaWNlbnNlXCI+XG4gIDxMaWNlbnNlTG9nbyAvPlxuPC9kaXY+XG5cbjxzdHlsZT5Aa2V5ZnJhbWVzIHNwaW5Bcm91bmQge1xuICBmcm9tIHtcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgwZGVnKTsgfVxuICB0byB7XG4gICAgdHJhbnNmb3JtOiByb3RhdGUoMzU5ZGVnKTsgfSB9XG5cbi50aXRsZSBpbWcge1xuICBoZWlnaHQ6IDNlbTsgfVxuXG4uaGVybyB7XG4gIGJhY2tncm91bmQtY29sb3I6ICMzMjVmNzQ7IH1cblxuLmxpY2Vuc2Uge1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHJpZ2h0OiAxZW07XG4gIGJvdHRvbTogMWVtOyB9XG5cbkBtZWRpYSBzY3JlZW4gYW5kIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gIC5tYXNjb3Qge1xuICAgIHdpZHRoOiA0NSU7XG4gICAgbWFyZ2luOiBhdXRvO1xuICAgIG1hcmdpbi10b3A6IC0zZW07IH0gfVxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=