(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["login~sign$45up"],{

/***/ "../lluis/FormField.svelte":
/*!*********************************!*\
  !*** ../lluis/FormField.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! lluis/Icon.svelte */ "../lluis/Icon.svelte");
/* home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/FormField.svelte generated by Svelte v3.25.0 */



const file = "home/trucnx/FPT/english/english4today.github.io/workspaces/lluis/FormField.svelte";

// (17:4) {#if type === "text"}
function create_if_block_2(ctx) {
	let input;
	let mounted;
	let dispose;

	const block = {
		c: function create() {
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			this.h();
		},
		l: function claim(nodes) {
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "INPUT", {
				class: true,
				type: true,
				name: true,
				id: true
			});

			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "input");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "text");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "name", /*id*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", /*id*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(input, "is-danger", /*error*/ ctx[5] != null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 17, 6, 374);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, input, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", /*input_input_handler*/ ctx[7]);
				mounted = true;
			}
		},
		p: function update(ctx, dirty) {
			if (dirty & /*id*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "name", /*id*/ ctx[2]);
			}

			if (dirty & /*id*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", /*id*/ ctx[2]);
			}

			if (dirty & /*value*/ 1 && input.value !== /*value*/ ctx[0]) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*value*/ ctx[0]);
			}

			if (dirty & /*error*/ 32) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(input, "is-danger", /*error*/ ctx[5] != null);
			}
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(input);
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_2.name,
		type: "if",
		source: "(17:4) {#if type === \\\"text\\\"}",
		ctx
	});

	return block;
}

// (26:4) {#if type === "password"}
function create_if_block_1(ctx) {
	let input;
	let mounted;
	let dispose;

	const block = {
		c: function create() {
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			this.h();
		},
		l: function claim(nodes) {
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "INPUT", {
				class: true,
				type: true,
				name: true,
				id: true
			});

			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "input");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "password");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "name", /*id*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", /*id*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(input, "is-danger", /*error*/ ctx[5] != null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 26, 6, 568);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, input, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", /*input_input_handler_1*/ ctx[8]);
				mounted = true;
			}
		},
		p: function update(ctx, dirty) {
			if (dirty & /*id*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "name", /*id*/ ctx[2]);
			}

			if (dirty & /*id*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", /*id*/ ctx[2]);
			}

			if (dirty & /*value*/ 1 && input.value !== /*value*/ ctx[0]) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*value*/ ctx[0]);
			}

			if (dirty & /*error*/ 32) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["toggle_class"])(input, "is-danger", /*error*/ ctx[5] != null);
			}
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(input);
			mounted = false;
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(26:4) {#if type === \\\"password\\\"}",
		ctx
	});

	return block;
}

// (37:2) {#if error != null}
function create_if_block(ctx) {
	let p;
	let t;

	const block = {
		c: function create() {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*error*/ ctx[5]);
			this.h();
		},
		l: function claim(nodes) {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, /*error*/ ctx[5]);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "help is-danger");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 37, 4, 808);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*error*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, /*error*/ ctx[5]);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(37:2) {#if error != null}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let div1;
	let label;
	let t0;
	let t1;
	let div0;
	let t2;
	let t3;
	let icon_1;
	let t4;
	let current;
	let if_block0 = /*type*/ ctx[4] === "text" && create_if_block_2(ctx);
	let if_block1 = /*type*/ ctx[4] === "password" && create_if_block_1(ctx);

	icon_1 = new lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({
			props: {
				size: "small",
				icon: /*icon*/ ctx[3],
				left: true
			},
			$$inline: true
		});

	let if_block2 = /*error*/ ctx[5] != null && create_if_block(ctx);

	const block = {
		c: function create() {
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*name*/ ctx[1]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			if (if_block0) if_block0.c();
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(icon_1.$$.fragment);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			this.h();
		},
		l: function claim(nodes) {
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "LABEL", { class: true, for: true });
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, /*name*/ ctx[1]);
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			if (if_block0) if_block0.l(div0_nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			if (if_block1) if_block1.l(div0_nodes);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(icon_1.$$.fragment, div0_nodes);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			if (if_block2) if_block2.l(div1_nodes);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "class", "label");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "for", /*id*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 14, 2, 258);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "control has-icons-left");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 15, 2, 305);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "field");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 13, 0, 236);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			if (if_block0) if_block0.m(div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t2);
			if (if_block1) if_block1.m(div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(icon_1, div0, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t4);
			if (if_block2) if_block2.m(div1, null);
			current = true;
		},
		p: function update(ctx, [dirty]) {
			if (!current || dirty & /*name*/ 2) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, /*name*/ ctx[1]);

			if (!current || dirty & /*id*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "for", /*id*/ ctx[2]);
			}

			if (/*type*/ ctx[4] === "text") {
				if (if_block0) {
					if_block0.p(ctx, dirty);
				} else {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(div0, t2);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (/*type*/ ctx[4] === "password") {
				if (if_block1) {
					if_block1.p(ctx, dirty);
				} else {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(div0, t3);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			const icon_1_changes = {};
			if (dirty & /*icon*/ 8) icon_1_changes.icon = /*icon*/ ctx[3];
			icon_1.$set(icon_1_changes);

			if (/*error*/ ctx[5] != null) {
				if (if_block2) {
					if_block2.p(ctx, dirty);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(div1, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(icon_1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(icon_1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div1);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(icon_1);
			if (if_block2) if_block2.d();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("FormField", slots, []);
	let { name } = $$props;
	let { id } = $$props;
	let { icon } = $$props;
	let { type = "text" } = $$props;
	let { value } = $$props;
	let { formStatus = {} } = $$props;
	let error = null;
	const writable_props = ["name", "id", "icon", "type", "value", "formStatus"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<FormField> was created with unknown prop '${key}'`);
	});

	function input_input_handler() {
		value = this.value;
		$$invalidate(0, value);
	}

	function input_input_handler_1() {
		value = this.value;
		$$invalidate(0, value);
	}

	$$self.$$set = $$props => {
		if ("name" in $$props) $$invalidate(1, name = $$props.name);
		if ("id" in $$props) $$invalidate(2, id = $$props.id);
		if ("icon" in $$props) $$invalidate(3, icon = $$props.icon);
		if ("type" in $$props) $$invalidate(4, type = $$props.type);
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
		if ("formStatus" in $$props) $$invalidate(6, formStatus = $$props.formStatus);
	};

	$$self.$capture_state = () => ({
		Icon: lluis_Icon_svelte__WEBPACK_IMPORTED_MODULE_1__["default"],
		name,
		id,
		icon,
		type,
		value,
		formStatus,
		error
	});

	$$self.$inject_state = $$props => {
		if ("name" in $$props) $$invalidate(1, name = $$props.name);
		if ("id" in $$props) $$invalidate(2, id = $$props.id);
		if ("icon" in $$props) $$invalidate(3, icon = $$props.icon);
		if ("type" in $$props) $$invalidate(4, type = $$props.type);
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
		if ("formStatus" in $$props) $$invalidate(6, formStatus = $$props.formStatus);
		if ("error" in $$props) $$invalidate(5, error = $$props.error);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*formStatus, id*/ 68) {
			$: {
				$$invalidate(5, error = formStatus[id]);
			}
		}
	};

	return [
		value,
		name,
		id,
		icon,
		type,
		error,
		formStatus,
		input_input_handler,
		input_input_handler_1
	];
}

class FormField extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {
			name: 1,
			id: 2,
			icon: 3,
			type: 4,
			value: 0,
			formStatus: 6
		});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "FormField",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*name*/ ctx[1] === undefined && !("name" in props)) {
			console.warn("<FormField> was created without expected prop 'name'");
		}

		if (/*id*/ ctx[2] === undefined && !("id" in props)) {
			console.warn("<FormField> was created without expected prop 'id'");
		}

		if (/*icon*/ ctx[3] === undefined && !("icon" in props)) {
			console.warn("<FormField> was created without expected prop 'icon'");
		}

		if (/*value*/ ctx[0] === undefined && !("value" in props)) {
			console.warn("<FormField> was created without expected prop 'value'");
		}
	}

	get name() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set name(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get id() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set id(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get icon() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set icon(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get type() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set type(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get value() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set value(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get formStatus() {
		throw new Error("<FormField>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set formStatus(value) {
		throw new Error("<FormField>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (FormField);

/***/ }),

/***/ "./src/db/db.js":
/*!**********************!*\
  !*** ./src/db/db.js ***!
  \**********************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(process) {/* harmony import */ var _settings__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../settings */ "./src/settings.js");
/* harmony import */ var _getUserDbName__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./getUserDbName */ "./src/db/getUserDbName.js");
/* harmony import */ var js_cookie__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! js-cookie */ "../../node_modules/js-cookie/src/js.cookie.js");
/* harmony import */ var js_cookie__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(js_cookie__WEBPACK_IMPORTED_MODULE_2__);




let db
let remoteDB
let syncHandler

const createLocalPouchDb = (dbName) => {
    const PouchDB =
    process.env.JEST_WORKER_ID !== undefined
        ? __webpack_require__(/*! pouchdb */ "../../node_modules/pouchdb/lib/index-browser.es.js")
        : __webpack_require__(/*! pouchdb */ "../../node_modules/pouchdb/lib/index-browser.es.js").default
    const newDb = new PouchDB(dbName).setMaxListeners(
        _settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.maxNumberOfListeners
    )

    newDb
        .changes({
            since: "now",
            live: true,
            include_docs: true,
        })
        .on("change", () => {
            if (process.env.JEST_WORKER_ID !== undefined) {
                return
            }
            const authStore = __webpack_require__(/*! ../auth */ "./src/auth.js").default
            authStore.update((value) => ({
                ...value,
                dbUpdatedAt: Date.now(),
            }))
        })

    return newDb
}

if (true) {
    const authStore = __webpack_require__(/*! ../auth */ "./src/auth.js").default
    const PouchDB = __webpack_require__(/*! pouchdb */ "../../node_modules/pouchdb/lib/index-browser.es.js").default

    // Connect to remote database
    remoteDB = new PouchDB(
        `${_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.remote}/${js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.get("loginDb")}`,
        { skip_setup: true, live: true }
    )

    // Connect to local database
    db = createLocalPouchDb(_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.local)
    window._DB = db

    // Detect fake user session
    if (js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.get("loginDb") === Object(_getUserDbName__WEBPACK_IMPORTED_MODULE_1__["default"])("---fakeUser")) {
        authStore.update((value) => ({
            ...value,
            user: { name: "---fakeUser" },
            online: true,
        }))
    }

    // Detect existing user session
    if (js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.get("loginDb") && _settings__WEBPACK_IMPORTED_MODULE_0__["default"].features.authEnabled) {
        fetch(`${_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.remote}/_session`, { credentials: "include" })
            .then((data) => data.json())
            .then((user) => {
                if (user.userCtx.name === null) {
                    return
                }
                authStore.update((value) => ({
                    ...value,
                    user: { name: user.userCtx.name },
                }))
                startSync()
            })
    } else {
    // Without a sessios, there is no sync
        authStore.update((value) => ({
            ...value,
            online: false,
        }))
    }

    // Fake login for testing purposes
    window._fakeLogin = () => {
        js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.set("loginDb", Object(_getUserDbName__WEBPACK_IMPORTED_MODULE_1__["default"])("---fakeUser"), {
            expires: _settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.auth.expireDays,
        })
        window.location.href = "/course/spanish-from-english/"
    }

    // Add login function
    window._Login = async (username, password) => {
        if (window._test_credentials_correct === false) {
            throw new Error("Incorrect username or password")
        }

        if (window._test_credentials_correct === true) {
            return window._fakeLogin()
        }

        const response = await (
            await fetch(`${_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.remote}/_session`, {
                method: "post",
                credentials: "include",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    username,
                    password,
                }),
            })
        ).json()

        if (response.error) {
            if (response.error === "unauthorized") {
                throw new Error("Username or password is incorrect")
            }
            throw new Error("Couldn't log in. Please try again later")
        }

        authStore.update((value) => ({
            ...value,
            online: null,
        }))
        js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.set("loginDb", Object(_getUserDbName__WEBPACK_IMPORTED_MODULE_1__["default"])(username), {
            expires: _settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.auth.expireDays,
        })
        window.location.reload(false)
        window.location.href = "/course/spanish-from-english/"
    }

    // Logout
    window._Logout = async () => {
        try {
            if (syncHandler) {
                await syncHandler.cancel()
                await fetch(`${_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.remote}/_session`, {
                    method: "delete",
                })
            }
        } finally {
            js_cookie__WEBPACK_IMPORTED_MODULE_2___default.a.remove("loginDb")
            authStore.update((value) => ({
                ...value,
                user: null,
                online: null,
            }))
            await db.destroy()
            window.location.reload(false)
        }
    }

    // Keep databases in sync
    const startSync = () => {
        syncHandler = db
            .sync(remoteDB)
            .on("complete", function () {
                authStore.update((value) => ({ ...value, online: true }))
            })
            .on("error", function () {
                authStore.update((value) => ({ ...value, online: false }))
            })
    }
}

if (process.env.JEST_WORKER_ID !== undefined) {
    // This is a test database for Jest tests that can reset itself
    db = createLocalPouchDb(_settings__WEBPACK_IMPORTED_MODULE_0__["default"].database.local)
    db.__reset = async () => {
        const allDocs = await db.allDocs()
        await Promise.all(
            allDocs.rows.map(function (row) {
                return db.remove(row.id, row.value.rev)
            })
        )
    }
}

/* harmony default export */ __webpack_exports__["default"] = (db);

/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../../../node_modules/process/browser.js */ "../../node_modules/process/browser.js")))

/***/ }),

/***/ "./src/db/getUserDbName.js":
/*!*********************************!*\
  !*** ./src/db/getUserDbName.js ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
const hashUsername = (username) =>
    username
        .split("")
        .map((c) => c.charCodeAt(0).toString(16))
        .join("")

/* harmony default export */ __webpack_exports__["default"] = ((username) => `userdb-${hashUsername(username)}`);


/***/ }),

/***/ 0:
/*!****************************!*\
  !*** ./nextTick (ignored) ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports) {

/* (ignored) */

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vbGx1aXMvRm9ybUZpZWxkLnN2ZWx0ZSIsIndlYnBhY2s6Ly8vLi9zcmMvZGIvZGIuanMiLCJ3ZWJwYWNrOi8vLy4vc3JjL2RiL2dldFVzZXJEYk5hbWUuanMiLCJ3ZWJwYWNrOi8vLy4vbmV4dFRpY2sgKGlnbm9yZWQpIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFDc0M7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzswRkFtQnhCLEdBQUU7d0ZBQ0osR0FBRTtzR0FDSSxHQUFLLE9BQUksSUFBSTs7Ozs7NEZBQ1YsR0FBSzs7Ozs7Ozs7OzJGQUhaLEdBQUU7Ozs7eUZBQ0osR0FBRTs7O3dEQUVPLEdBQUs7NkZBQUwsR0FBSzs7Ozt1R0FEUixHQUFLLE9BQUksSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBGQU9qQixHQUFFO3dGQUNKLEdBQUU7c0dBQ0ksR0FBSyxPQUFJLElBQUk7Ozs7OzRGQUNWLEdBQUs7Ozs7Ozs7OzsyRkFIWixHQUFFOzs7O3lGQUNKLEdBQUU7Ozt3REFFTyxHQUFLOzZGQUFMLEdBQUs7Ozs7dUdBRFIsR0FBSyxPQUFJLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhFQU1BLEdBQUs7Ozs7Ozs2RkFBTCxHQUFLOzs7Ozs7Ozs7Ozs7OytHQUFMLEdBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQXJCM0IsR0FBSSxRQUFLLE1BQU07MEJBU2YsR0FBSSxRQUFLLFVBQVU7Ozs7O21CQVNDLEdBQUk7Ozs7OzsyQkFFMUIsR0FBSyxPQUFJLElBQUk7Ozs7Ozs4RUF0QmEsR0FBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7aUdBQUosR0FBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lGQUFULEdBQUU7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lIQUFHLEdBQUk7OzswRkFBVCxHQUFFOzs7Z0JBRXJCLEdBQUksUUFBSyxNQUFNOzs7Ozs7Ozs7Ozs7O2dCQVNmLEdBQUksUUFBSyxVQUFVOzs7Ozs7Ozs7Ozs7OzswREFTQyxHQUFJOzs7aUJBRTFCLEdBQUssT0FBSSxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7T0FqQ1AsSUFBSTtPQUNKLEVBQUU7T0FDRixJQUFJO09BQ0osSUFBSSxHQUFHLE1BQU07T0FDYixLQUFLO09BQ0wsVUFBVTtLQUNqQixLQUFLLEdBQUcsSUFBSTs7Ozs7Ozs7RUFjRyxLQUFLOzs7OztFQVNMLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7R0F0QnhCLENBQUM7b0JBQUcsS0FBSyxHQUFHLFVBQVUsQ0FBQyxFQUFFOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ1YzQjtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQWtDO0FBQ1M7QUFDWjs7QUFFL0I7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBLFVBQVUsbUJBQU8sQ0FBQyxtRUFBUztBQUMzQixVQUFVLG1CQUFPLENBQUMsbUVBQVM7QUFDM0I7QUFDQSxRQUFRLGlEQUFRO0FBQ2hCOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxTQUFTO0FBQ1Q7QUFDQTtBQUNBO0FBQ0E7QUFDQSw4QkFBOEIsbUJBQU8sQ0FBQyw4QkFBUztBQUMvQztBQUNBO0FBQ0E7QUFDQSxhQUFhO0FBQ2IsU0FBUzs7QUFFVDtBQUNBOztBQUVBLElBQUksSUFBd0I7QUFDNUIsc0JBQXNCLG1CQUFPLENBQUMsOEJBQVM7QUFDdkMsb0JBQW9CLG1CQUFPLENBQUMsbUVBQVM7O0FBRXJDO0FBQ0E7QUFDQSxXQUFXLGlEQUFRLGlCQUFpQixHQUFHLGdEQUFPLGdCQUFnQjtBQUM5RCxTQUFTO0FBQ1Q7O0FBRUE7QUFDQSw0QkFBNEIsaURBQVE7QUFDcEM7O0FBRUE7QUFDQSxRQUFRLGdEQUFPLG9CQUFvQiw4REFBYTtBQUNoRDtBQUNBO0FBQ0EsbUJBQW1CLHNCQUFzQjtBQUN6QztBQUNBLFNBQVM7QUFDVDs7QUFFQTtBQUNBLFFBQVEsZ0RBQU8sbUJBQW1CLGlEQUFRO0FBQzFDLGlCQUFpQixpREFBUSxpQkFBaUIsYUFBYSx5QkFBeUI7QUFDaEY7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSwyQkFBMkIsMEJBQTBCO0FBQ3JELGlCQUFpQjtBQUNqQjtBQUNBLGFBQWE7QUFDYixLQUFLO0FBQ0w7QUFDQTtBQUNBO0FBQ0E7QUFDQSxTQUFTO0FBQ1Q7O0FBRUE7QUFDQTtBQUNBLFFBQVEsZ0RBQU8sZ0JBQWdCLDhEQUFhO0FBQzVDLHFCQUFxQixpREFBUTtBQUM3QixTQUFTO0FBQ1Q7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBLDJCQUEyQixpREFBUSxpQkFBaUI7QUFDcEQ7QUFDQTtBQUNBO0FBQ0E7QUFDQSxpQkFBaUI7QUFDakI7QUFDQTtBQUNBO0FBQ0EsaUJBQWlCO0FBQ2pCLGFBQWE7QUFDYjs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0EsU0FBUztBQUNULFFBQVEsZ0RBQU8sZ0JBQWdCLDhEQUFhO0FBQzVDLHFCQUFxQixpREFBUTtBQUM3QixTQUFTO0FBQ1Q7QUFDQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSwrQkFBK0IsaURBQVEsaUJBQWlCO0FBQ3hEO0FBQ0EsaUJBQWlCO0FBQ2pCO0FBQ0EsU0FBUztBQUNULFlBQVksZ0RBQU87QUFDbkI7QUFDQTtBQUNBO0FBQ0E7QUFDQSxhQUFhO0FBQ2I7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLDhDQUE4Qyx5QkFBeUI7QUFDdkUsYUFBYTtBQUNiO0FBQ0EsOENBQThDLDBCQUEwQjtBQUN4RSxhQUFhO0FBQ2I7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsNEJBQTRCLGlEQUFRO0FBQ3BDO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxhQUFhO0FBQ2I7QUFDQTtBQUNBOztBQUVlLGlFQUFFOzs7Ozs7Ozs7Ozs7OztBQ25MakI7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQUVlLHVGQUF3Qix1QkFBdUIsQ0FBQzs7Ozs7Ozs7Ozs7O0FDTi9ELGUiLCJmaWxlIjoiYWViZTlmMGYyZjEwODY1YmY0YmQvbG9naW5+c2lnbiQ0NXVwLmxvZ2lufnNpZ24kNDV1cC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGltcG9ydCBJY29uIGZyb20gXCJsbHVpcy9JY29uLnN2ZWx0ZVwiXG5cbiAgZXhwb3J0IGxldCBuYW1lXG4gIGV4cG9ydCBsZXQgaWRcbiAgZXhwb3J0IGxldCBpY29uXG4gIGV4cG9ydCBsZXQgdHlwZSA9IFwidGV4dFwiXG4gIGV4cG9ydCBsZXQgdmFsdWVcbiAgZXhwb3J0IGxldCBmb3JtU3RhdHVzID0ge31cbiAgbGV0IGVycm9yID0gbnVsbFxuICAkOiB7ZXJyb3IgPSBmb3JtU3RhdHVzW2lkXX1cbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiZmllbGRcIj5cbiAgPGxhYmVsIGNsYXNzPVwibGFiZWxcIiBmb3I9e2lkfT57bmFtZX08L2xhYmVsPlxuICA8ZGl2IGNsYXNzPVwiY29udHJvbCBoYXMtaWNvbnMtbGVmdFwiPlxuICAgIHsjaWYgdHlwZSA9PT0gXCJ0ZXh0XCJ9XG4gICAgICA8aW5wdXRcbiAgICAgICAgY2xhc3M9XCJpbnB1dFwiXG4gICAgICAgIHR5cGU9XCJ0ZXh0XCJcbiAgICAgICAgbmFtZT17aWR9XG4gICAgICAgIGlkPXtpZH1cblx0Y2xhc3M6aXMtZGFuZ2VyPXtlcnJvciAhPSBudWxsfVxuICAgICAgICBiaW5kOnZhbHVlPVwie3ZhbHVlfVwiIC8+XG4gICAgey9pZn1cbiAgICB7I2lmIHR5cGUgPT09IFwicGFzc3dvcmRcIn1cbiAgICAgIDxpbnB1dFxuICAgICAgICBjbGFzcz1cImlucHV0XCJcbiAgICAgICAgdHlwZT1cInBhc3N3b3JkXCJcbiAgICAgICAgbmFtZT17aWR9XG4gICAgICAgIGlkPXtpZH1cblx0Y2xhc3M6aXMtZGFuZ2VyPXtlcnJvciAhPSBudWxsfVxuICAgICAgICBiaW5kOnZhbHVlPVwie3ZhbHVlfVwiIC8+XG4gICAgey9pZn1cbiAgICA8SWNvbiBzaXplPVwic21hbGxcIiBpY29uPXtpY29ufSBsZWZ0IC8+XG4gIDwvZGl2PlxuICB7I2lmIGVycm9yICE9IG51bGx9XG4gICAgPHAgY2xhc3M9XCJoZWxwIGlzLWRhbmdlclwiPntlcnJvcn08L3A+XG4gIHsvaWZ9XG48L2Rpdj5cbiIsImltcG9ydCBzZXR0aW5ncyBmcm9tIFwiLi4vc2V0dGluZ3NcIlxuaW1wb3J0IGdldFVzZXJEYk5hbWUgZnJvbSBcIi4vZ2V0VXNlckRiTmFtZVwiXG5pbXBvcnQgQ29va2llcyBmcm9tIFwianMtY29va2llXCJcblxubGV0IGRiXG5sZXQgcmVtb3RlREJcbmxldCBzeW5jSGFuZGxlclxuXG5jb25zdCBjcmVhdGVMb2NhbFBvdWNoRGIgPSAoZGJOYW1lKSA9PiB7XG4gICAgY29uc3QgUG91Y2hEQiA9XG4gICAgcHJvY2Vzcy5lbnYuSkVTVF9XT1JLRVJfSUQgIT09IHVuZGVmaW5lZFxuICAgICAgICA/IHJlcXVpcmUoXCJwb3VjaGRiXCIpXG4gICAgICAgIDogcmVxdWlyZShcInBvdWNoZGJcIikuZGVmYXVsdFxuICAgIGNvbnN0IG5ld0RiID0gbmV3IFBvdWNoREIoZGJOYW1lKS5zZXRNYXhMaXN0ZW5lcnMoXG4gICAgICAgIHNldHRpbmdzLmRhdGFiYXNlLm1heE51bWJlck9mTGlzdGVuZXJzXG4gICAgKVxuXG4gICAgbmV3RGJcbiAgICAgICAgLmNoYW5nZXMoe1xuICAgICAgICAgICAgc2luY2U6IFwibm93XCIsXG4gICAgICAgICAgICBsaXZlOiB0cnVlLFxuICAgICAgICAgICAgaW5jbHVkZV9kb2NzOiB0cnVlLFxuICAgICAgICB9KVxuICAgICAgICAub24oXCJjaGFuZ2VcIiwgKCkgPT4ge1xuICAgICAgICAgICAgaWYgKHByb2Nlc3MuZW52LkpFU1RfV09SS0VSX0lEICE9PSB1bmRlZmluZWQpIHtcbiAgICAgICAgICAgICAgICByZXR1cm5cbiAgICAgICAgICAgIH1cbiAgICAgICAgICAgIGNvbnN0IGF1dGhTdG9yZSA9IHJlcXVpcmUoXCIuLi9hdXRoXCIpLmRlZmF1bHRcbiAgICAgICAgICAgIGF1dGhTdG9yZS51cGRhdGUoKHZhbHVlKSA9PiAoe1xuICAgICAgICAgICAgICAgIC4uLnZhbHVlLFxuICAgICAgICAgICAgICAgIGRiVXBkYXRlZEF0OiBEYXRlLm5vdygpLFxuICAgICAgICAgICAgfSkpXG4gICAgICAgIH0pXG5cbiAgICByZXR1cm4gbmV3RGJcbn1cblxuaWYgKHByb2Nlc3MuYnJvd3NlciA9PT0gdHJ1ZSkge1xuICAgIGNvbnN0IGF1dGhTdG9yZSA9IHJlcXVpcmUoXCIuLi9hdXRoXCIpLmRlZmF1bHRcbiAgICBjb25zdCBQb3VjaERCID0gcmVxdWlyZShcInBvdWNoZGJcIikuZGVmYXVsdFxuXG4gICAgLy8gQ29ubmVjdCB0byByZW1vdGUgZGF0YWJhc2VcbiAgICByZW1vdGVEQiA9IG5ldyBQb3VjaERCKFxuICAgICAgICBgJHtzZXR0aW5ncy5kYXRhYmFzZS5yZW1vdGV9LyR7Q29va2llcy5nZXQoXCJsb2dpbkRiXCIpfWAsXG4gICAgICAgIHsgc2tpcF9zZXR1cDogdHJ1ZSwgbGl2ZTogdHJ1ZSB9XG4gICAgKVxuXG4gICAgLy8gQ29ubmVjdCB0byBsb2NhbCBkYXRhYmFzZVxuICAgIGRiID0gY3JlYXRlTG9jYWxQb3VjaERiKHNldHRpbmdzLmRhdGFiYXNlLmxvY2FsKVxuICAgIHdpbmRvdy5fREIgPSBkYlxuXG4gICAgLy8gRGV0ZWN0IGZha2UgdXNlciBzZXNzaW9uXG4gICAgaWYgKENvb2tpZXMuZ2V0KFwibG9naW5EYlwiKSA9PT0gZ2V0VXNlckRiTmFtZShcIi0tLWZha2VVc2VyXCIpKSB7XG4gICAgICAgIGF1dGhTdG9yZS51cGRhdGUoKHZhbHVlKSA9PiAoe1xuICAgICAgICAgICAgLi4udmFsdWUsXG4gICAgICAgICAgICB1c2VyOiB7IG5hbWU6IFwiLS0tZmFrZVVzZXJcIiB9LFxuICAgICAgICAgICAgb25saW5lOiB0cnVlLFxuICAgICAgICB9KSlcbiAgICB9XG5cbiAgICAvLyBEZXRlY3QgZXhpc3RpbmcgdXNlciBzZXNzaW9uXG4gICAgaWYgKENvb2tpZXMuZ2V0KFwibG9naW5EYlwiKSAmJiBzZXR0aW5ncy5mZWF0dXJlcy5hdXRoRW5hYmxlZCkge1xuICAgICAgICBmZXRjaChgJHtzZXR0aW5ncy5kYXRhYmFzZS5yZW1vdGV9L19zZXNzaW9uYCwgeyBjcmVkZW50aWFsczogXCJpbmNsdWRlXCIgfSlcbiAgICAgICAgICAgIC50aGVuKChkYXRhKSA9PiBkYXRhLmpzb24oKSlcbiAgICAgICAgICAgIC50aGVuKCh1c2VyKSA9PiB7XG4gICAgICAgICAgICAgICAgaWYgKHVzZXIudXNlckN0eC5uYW1lID09PSBudWxsKSB7XG4gICAgICAgICAgICAgICAgICAgIHJldHVyblxuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgICAgICBhdXRoU3RvcmUudXBkYXRlKCh2YWx1ZSkgPT4gKHtcbiAgICAgICAgICAgICAgICAgICAgLi4udmFsdWUsXG4gICAgICAgICAgICAgICAgICAgIHVzZXI6IHsgbmFtZTogdXNlci51c2VyQ3R4Lm5hbWUgfSxcbiAgICAgICAgICAgICAgICB9KSlcbiAgICAgICAgICAgICAgICBzdGFydFN5bmMoKVxuICAgICAgICAgICAgfSlcbiAgICB9IGVsc2Uge1xuICAgIC8vIFdpdGhvdXQgYSBzZXNzaW9zLCB0aGVyZSBpcyBubyBzeW5jXG4gICAgICAgIGF1dGhTdG9yZS51cGRhdGUoKHZhbHVlKSA9PiAoe1xuICAgICAgICAgICAgLi4udmFsdWUsXG4gICAgICAgICAgICBvbmxpbmU6IGZhbHNlLFxuICAgICAgICB9KSlcbiAgICB9XG5cbiAgICAvLyBGYWtlIGxvZ2luIGZvciB0ZXN0aW5nIHB1cnBvc2VzXG4gICAgd2luZG93Ll9mYWtlTG9naW4gPSAoKSA9PiB7XG4gICAgICAgIENvb2tpZXMuc2V0KFwibG9naW5EYlwiLCBnZXRVc2VyRGJOYW1lKFwiLS0tZmFrZVVzZXJcIiksIHtcbiAgICAgICAgICAgIGV4cGlyZXM6IHNldHRpbmdzLmRhdGFiYXNlLmF1dGguZXhwaXJlRGF5cyxcbiAgICAgICAgfSlcbiAgICAgICAgd2luZG93LmxvY2F0aW9uLmhyZWYgPSBcIi9jb3Vyc2Uvc3BhbmlzaC1mcm9tLWVuZ2xpc2gvXCJcbiAgICB9XG5cbiAgICAvLyBBZGQgbG9naW4gZnVuY3Rpb25cbiAgICB3aW5kb3cuX0xvZ2luID0gYXN5bmMgKHVzZXJuYW1lLCBwYXNzd29yZCkgPT4ge1xuICAgICAgICBpZiAod2luZG93Ll90ZXN0X2NyZWRlbnRpYWxzX2NvcnJlY3QgPT09IGZhbHNlKSB7XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXCJJbmNvcnJlY3QgdXNlcm5hbWUgb3IgcGFzc3dvcmRcIilcbiAgICAgICAgfVxuXG4gICAgICAgIGlmICh3aW5kb3cuX3Rlc3RfY3JlZGVudGlhbHNfY29ycmVjdCA9PT0gdHJ1ZSkge1xuICAgICAgICAgICAgcmV0dXJuIHdpbmRvdy5fZmFrZUxvZ2luKClcbiAgICAgICAgfVxuXG4gICAgICAgIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgKFxuICAgICAgICAgICAgYXdhaXQgZmV0Y2goYCR7c2V0dGluZ3MuZGF0YWJhc2UucmVtb3RlfS9fc2Vzc2lvbmAsIHtcbiAgICAgICAgICAgICAgICBtZXRob2Q6IFwicG9zdFwiLFxuICAgICAgICAgICAgICAgIGNyZWRlbnRpYWxzOiBcImluY2x1ZGVcIixcbiAgICAgICAgICAgICAgICBoZWFkZXJzOiB7XG4gICAgICAgICAgICAgICAgICAgIFwiQ29udGVudC1UeXBlXCI6IFwiYXBwbGljYXRpb24vanNvblwiLFxuICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkoe1xuICAgICAgICAgICAgICAgICAgICB1c2VybmFtZSxcbiAgICAgICAgICAgICAgICAgICAgcGFzc3dvcmQsXG4gICAgICAgICAgICAgICAgfSksXG4gICAgICAgICAgICB9KVxuICAgICAgICApLmpzb24oKVxuXG4gICAgICAgIGlmIChyZXNwb25zZS5lcnJvcikge1xuICAgICAgICAgICAgaWYgKHJlc3BvbnNlLmVycm9yID09PSBcInVuYXV0aG9yaXplZFwiKSB7XG4gICAgICAgICAgICAgICAgdGhyb3cgbmV3IEVycm9yKFwiVXNlcm5hbWUgb3IgcGFzc3dvcmQgaXMgaW5jb3JyZWN0XCIpXG4gICAgICAgICAgICB9XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXCJDb3VsZG4ndCBsb2cgaW4uIFBsZWFzZSB0cnkgYWdhaW4gbGF0ZXJcIilcbiAgICAgICAgfVxuXG4gICAgICAgIGF1dGhTdG9yZS51cGRhdGUoKHZhbHVlKSA9PiAoe1xuICAgICAgICAgICAgLi4udmFsdWUsXG4gICAgICAgICAgICBvbmxpbmU6IG51bGwsXG4gICAgICAgIH0pKVxuICAgICAgICBDb29raWVzLnNldChcImxvZ2luRGJcIiwgZ2V0VXNlckRiTmFtZSh1c2VybmFtZSksIHtcbiAgICAgICAgICAgIGV4cGlyZXM6IHNldHRpbmdzLmRhdGFiYXNlLmF1dGguZXhwaXJlRGF5cyxcbiAgICAgICAgfSlcbiAgICAgICAgd2luZG93LmxvY2F0aW9uLnJlbG9hZChmYWxzZSlcbiAgICAgICAgd2luZG93LmxvY2F0aW9uLmhyZWYgPSBcIi9jb3Vyc2Uvc3BhbmlzaC1mcm9tLWVuZ2xpc2gvXCJcbiAgICB9XG5cbiAgICAvLyBMb2dvdXRcbiAgICB3aW5kb3cuX0xvZ291dCA9IGFzeW5jICgpID0+IHtcbiAgICAgICAgdHJ5IHtcbiAgICAgICAgICAgIGlmIChzeW5jSGFuZGxlcikge1xuICAgICAgICAgICAgICAgIGF3YWl0IHN5bmNIYW5kbGVyLmNhbmNlbCgpXG4gICAgICAgICAgICAgICAgYXdhaXQgZmV0Y2goYCR7c2V0dGluZ3MuZGF0YWJhc2UucmVtb3RlfS9fc2Vzc2lvbmAsIHtcbiAgICAgICAgICAgICAgICAgICAgbWV0aG9kOiBcImRlbGV0ZVwiLFxuICAgICAgICAgICAgICAgIH0pXG4gICAgICAgICAgICB9XG4gICAgICAgIH0gZmluYWxseSB7XG4gICAgICAgICAgICBDb29raWVzLnJlbW92ZShcImxvZ2luRGJcIilcbiAgICAgICAgICAgIGF1dGhTdG9yZS51cGRhdGUoKHZhbHVlKSA9PiAoe1xuICAgICAgICAgICAgICAgIC4uLnZhbHVlLFxuICAgICAgICAgICAgICAgIHVzZXI6IG51bGwsXG4gICAgICAgICAgICAgICAgb25saW5lOiBudWxsLFxuICAgICAgICAgICAgfSkpXG4gICAgICAgICAgICBhd2FpdCBkYi5kZXN0cm95KClcbiAgICAgICAgICAgIHdpbmRvdy5sb2NhdGlvbi5yZWxvYWQoZmFsc2UpXG4gICAgICAgIH1cbiAgICB9XG5cbiAgICAvLyBLZWVwIGRhdGFiYXNlcyBpbiBzeW5jXG4gICAgY29uc3Qgc3RhcnRTeW5jID0gKCkgPT4ge1xuICAgICAgICBzeW5jSGFuZGxlciA9IGRiXG4gICAgICAgICAgICAuc3luYyhyZW1vdGVEQilcbiAgICAgICAgICAgIC5vbihcImNvbXBsZXRlXCIsIGZ1bmN0aW9uICgpIHtcbiAgICAgICAgICAgICAgICBhdXRoU3RvcmUudXBkYXRlKCh2YWx1ZSkgPT4gKHsgLi4udmFsdWUsIG9ubGluZTogdHJ1ZSB9KSlcbiAgICAgICAgICAgIH0pXG4gICAgICAgICAgICAub24oXCJlcnJvclwiLCBmdW5jdGlvbiAoKSB7XG4gICAgICAgICAgICAgICAgYXV0aFN0b3JlLnVwZGF0ZSgodmFsdWUpID0+ICh7IC4uLnZhbHVlLCBvbmxpbmU6IGZhbHNlIH0pKVxuICAgICAgICAgICAgfSlcbiAgICB9XG59XG5cbmlmIChwcm9jZXNzLmVudi5KRVNUX1dPUktFUl9JRCAhPT0gdW5kZWZpbmVkKSB7XG4gICAgLy8gVGhpcyBpcyBhIHRlc3QgZGF0YWJhc2UgZm9yIEplc3QgdGVzdHMgdGhhdCBjYW4gcmVzZXQgaXRzZWxmXG4gICAgZGIgPSBjcmVhdGVMb2NhbFBvdWNoRGIoc2V0dGluZ3MuZGF0YWJhc2UubG9jYWwpXG4gICAgZGIuX19yZXNldCA9IGFzeW5jICgpID0+IHtcbiAgICAgICAgY29uc3QgYWxsRG9jcyA9IGF3YWl0IGRiLmFsbERvY3MoKVxuICAgICAgICBhd2FpdCBQcm9taXNlLmFsbChcbiAgICAgICAgICAgIGFsbERvY3Mucm93cy5tYXAoZnVuY3Rpb24gKHJvdykge1xuICAgICAgICAgICAgICAgIHJldHVybiBkYi5yZW1vdmUocm93LmlkLCByb3cudmFsdWUucmV2KVxuICAgICAgICAgICAgfSlcbiAgICAgICAgKVxuICAgIH1cbn1cblxuZXhwb3J0IGRlZmF1bHQgZGJcbiIsImNvbnN0IGhhc2hVc2VybmFtZSA9ICh1c2VybmFtZSkgPT5cbiAgICB1c2VybmFtZVxuICAgICAgICAuc3BsaXQoXCJcIilcbiAgICAgICAgLm1hcCgoYykgPT4gYy5jaGFyQ29kZUF0KDApLnRvU3RyaW5nKDE2KSlcbiAgICAgICAgLmpvaW4oXCJcIilcblxuZXhwb3J0IGRlZmF1bHQgKHVzZXJuYW1lKSA9PiBgdXNlcmRiLSR7aGFzaFVzZXJuYW1lKHVzZXJuYW1lKX1gXG4iLCIvKiAoaWdub3JlZCkgKi8iXSwic291cmNlUm9vdCI6IiJ9