(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["sign$45up"],{

/***/ "./src/routes/sign-up.svelte":
/*!***********************************!*\
  !*** ./src/routes/sign-up.svelte ***!
  \***********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _db_db_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../db/db.js */ "./src/db/db.js");
/* harmony import */ var _settings__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../settings */ "./src/settings.js");
/* harmony import */ var _components_NavBar_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/NavBar.svelte */ "./src/components/NavBar.svelte");
/* harmony import */ var lluis_Button__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! lluis/Button */ "../lluis/Button.svelte");
/* harmony import */ var lluis_FormField__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! lluis/FormField */ "../lluis/FormField.svelte");
/* src/routes/sign-up.svelte generated by Svelte v3.25.0 */


const { Object: Object_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];





const file = "src/routes/sign-up.svelte";

// (243:8) {#if errors['license'] != null}
function create_if_block_1(ctx) {
	let p;
	let t_value = /*errors*/ ctx[6]["license"] + "";
	let t;

	const block = {
		c: function create() {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, t_value);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "help is-danger");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 243, 10, 5554);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*errors*/ 64 && t_value !== (t_value = /*errors*/ ctx[6]["license"] + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block_1.name,
		type: "if",
		source: "(243:8) {#if errors['license'] != null}",
		ctx
	});

	return block;
}

// (248:6) {#if errors._form != null}
function create_if_block(ctx) {
	let p;
	let t_value = /*errors*/ ctx[6]._form + "";
	let t;

	const block = {
		c: function create() {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, t_value);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "help is-danger");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 248, 8, 5673);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t);
		},
		p: function update(ctx, dirty) {
			if (dirty & /*errors*/ 64 && t_value !== (t_value = /*errors*/ ctx[6]._form + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_if_block.name,
		type: "if",
		source: "(248:6) {#if errors._form != null}",
		ctx
	});

	return block;
}

// (252:6) <Button         on:click="{handleSignUp}"         {loading}         asHref="/sign-up-success"         submit>
function create_default_slot(ctx) {
	let t;

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Sign up");
		},
		l: function claim(nodes) {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "Sign up");
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_default_slot.name,
		type: "slot",
		source: "(252:6) <Button         on:click=\\\"{handleSignUp}\\\"         {loading}         asHref=\\\"/sign-up-success\\\"         submit>",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t0;
	let navbar;
	let t1;
	let section;
	let div2;
	let form;
	let h2;
	let t2;
	let t3;
	let formfield0;
	let updating_value;
	let t4;
	let formfield1;
	let updating_value_1;
	let t5;
	let formfield2;
	let updating_value_2;
	let t6;
	let formfield3;
	let updating_value_3;
	let t7;
	let div1;
	let div0;
	let label;
	let input;
	let t8;
	let a0;
	let t9;
	let t10;
	let a1;
	let t11;
	let t12;
	let t13;
	let t14;
	let button;
	let current;
	let mounted;
	let dispose;
	navbar = new _components_NavBar_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({ props: { dark: true }, $$inline: true });

	function formfield0_value_binding(value) {
		/*formfield0_value_binding*/ ctx[8].call(null, value);
	}

	let formfield0_props = {
		name: "Username",
		icon: "user",
		id: "username",
		formStatus: /*errors*/ ctx[6]
	};

	if (/*username*/ ctx[1] !== void 0) {
		formfield0_props.value = /*username*/ ctx[1];
	}

	formfield0 = new lluis_FormField__WEBPACK_IMPORTED_MODULE_5__["default"]({ props: formfield0_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formfield0, "value", formfield0_value_binding));

	function formfield1_value_binding(value) {
		/*formfield1_value_binding*/ ctx[9].call(null, value);
	}

	let formfield1_props = {
		name: "Email",
		icon: "envelope",
		id: "email",
		formStatus: /*errors*/ ctx[6]
	};

	if (/*email*/ ctx[2] !== void 0) {
		formfield1_props.value = /*email*/ ctx[2];
	}

	formfield1 = new lluis_FormField__WEBPACK_IMPORTED_MODULE_5__["default"]({ props: formfield1_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formfield1, "value", formfield1_value_binding));

	function formfield2_value_binding(value) {
		/*formfield2_value_binding*/ ctx[10].call(null, value);
	}

	let formfield2_props = {
		name: "Password",
		icon: "lock",
		id: "password",
		type: "password",
		formStatus: /*errors*/ ctx[6]
	};

	if (/*password*/ ctx[3] !== void 0) {
		formfield2_props.value = /*password*/ ctx[3];
	}

	formfield2 = new lluis_FormField__WEBPACK_IMPORTED_MODULE_5__["default"]({ props: formfield2_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formfield2, "value", formfield2_value_binding));

	function formfield3_value_binding(value) {
		/*formfield3_value_binding*/ ctx[11].call(null, value);
	}

	let formfield3_props = {
		name: "Repeat password",
		icon: "lock",
		id: "password_confirmation",
		type: "password",
		formStatus: /*errors*/ ctx[6]
	};

	if (/*password_confirmation*/ ctx[4] !== void 0) {
		formfield3_props.value = /*password_confirmation*/ ctx[4];
	}

	formfield3 = new lluis_FormField__WEBPACK_IMPORTED_MODULE_5__["default"]({ props: formfield3_props, $$inline: true });
	svelte_internal__WEBPACK_IMPORTED_MODULE_0__["binding_callbacks"].push(() => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["bind"])(formfield3, "value", formfield3_value_binding));
	let if_block0 = /*errors*/ ctx[6]["license"] != null && create_if_block_1(ctx);
	let if_block1 = /*errors*/ ctx[6]._form != null && create_if_block(ctx);

	button = new lluis_Button__WEBPACK_IMPORTED_MODULE_4__["default"]({
			props: {
				loading: /*loading*/ ctx[0],
				asHref: "/sign-up-success",
				submit: true,
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			},
			$$inline: true
		});

	button.$on("click", function () {
		if (Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(/*handleSignUp*/ ctx[7])) /*handleSignUp*/ ctx[7].apply(this, arguments);
	});

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(navbar.$$.fragment);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			form = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("form");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Sign up");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(formfield0.$$.fragment);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(formfield1.$$.fragment);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(formfield2.$$.fragment);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(formfield3.$$.fragment);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            I agree to the\n            ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Terms and Conditions");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            and the\n            ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GNU Affero General Public License");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block0) if_block0.c();
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(button.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1n7oua1\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(navbar.$$.fragment, nodes);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			form = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "FORM", {});
			var form_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(form);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(form_nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Sign up");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(formfield0.$$.fragment, form_nodes);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(formfield1.$$.fragment, form_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(formfield2.$$.fragment, form_nodes);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(formfield3.$$.fragment, form_nodes);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(form_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "LABEL", { class: true });
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(label_nodes, "INPUT", { type: true, name: true, id: true });
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, "\n            I agree to the\n            ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(label_nodes, "A", { href: true });
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "Terms and Conditions");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, "\n            and the\n            ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(label_nodes, "A", { href: true });
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "GNU Affero General Public License");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			if (if_block0) if_block0.l(div1_nodes);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			if (if_block1) if_block1.l(form_nodes);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(form_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(button.$$.fragment, form_nodes);
			form_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Sign up - LibreLingo";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "is-size-2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 199, 6, 4350);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "checkbox");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "name", "license");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "id", "license");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 231, 12, 5158);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", "/tos");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 237, 12, 5341);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", "/license");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 239, 12, 5413);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "class", "checkbox");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 230, 10, 5121);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "control");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 229, 8, 5089);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "field");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 228, 6, 5061);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(form, file, 198, 4, 4295);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 196, 2, 4266);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "section");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 194, 0, 4237);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(navbar, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, form);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formfield0, form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formfield1, form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formfield2, form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(formfield3, form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, input);
			input.checked = /*license_accepted*/ ctx[5];
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t12);
			if (if_block0) if_block0.m(div1, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t13);
			if (if_block1) if_block1.m(form, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(form, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(button, form, null);
			current = true;

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "change", /*input_change_handler*/ ctx[12]),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(
						form,
						"submit",
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prevent_default"])(function () {
							if (Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(/*handleSignUp*/ ctx[7])) /*handleSignUp*/ ctx[7].apply(this, arguments);
						}),
						false,
						true,
						false
					)
				];

				mounted = true;
			}
		},
		p: function update(new_ctx, [dirty]) {
			ctx = new_ctx;
			const formfield0_changes = {};
			if (dirty & /*errors*/ 64) formfield0_changes.formStatus = /*errors*/ ctx[6];

			if (!updating_value && dirty & /*username*/ 2) {
				updating_value = true;
				formfield0_changes.value = /*username*/ ctx[1];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value = false);
			}

			formfield0.$set(formfield0_changes);
			const formfield1_changes = {};
			if (dirty & /*errors*/ 64) formfield1_changes.formStatus = /*errors*/ ctx[6];

			if (!updating_value_1 && dirty & /*email*/ 4) {
				updating_value_1 = true;
				formfield1_changes.value = /*email*/ ctx[2];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value_1 = false);
			}

			formfield1.$set(formfield1_changes);
			const formfield2_changes = {};
			if (dirty & /*errors*/ 64) formfield2_changes.formStatus = /*errors*/ ctx[6];

			if (!updating_value_2 && dirty & /*password*/ 8) {
				updating_value_2 = true;
				formfield2_changes.value = /*password*/ ctx[3];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value_2 = false);
			}

			formfield2.$set(formfield2_changes);
			const formfield3_changes = {};
			if (dirty & /*errors*/ 64) formfield3_changes.formStatus = /*errors*/ ctx[6];

			if (!updating_value_3 && dirty & /*password_confirmation*/ 16) {
				updating_value_3 = true;
				formfield3_changes.value = /*password_confirmation*/ ctx[4];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_flush_callback"])(() => updating_value_3 = false);
			}

			formfield3.$set(formfield3_changes);

			if (dirty & /*license_accepted*/ 32) {
				input.checked = /*license_accepted*/ ctx[5];
			}

			if (/*errors*/ ctx[6]["license"] != null) {
				if (if_block0) {
					if_block0.p(ctx, dirty);
				} else {
					if_block0 = create_if_block_1(ctx);
					if_block0.c();
					if_block0.m(div1, null);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (/*errors*/ ctx[6]._form != null) {
				if (if_block1) {
					if_block1.p(ctx, dirty);
				} else {
					if_block1 = create_if_block(ctx);
					if_block1.c();
					if_block1.m(form, t14);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			const button_changes = {};
			if (dirty & /*loading*/ 1) button_changes.loading = /*loading*/ ctx[0];

			if (dirty & /*$$scope*/ 262144) {
				button_changes.$$scope = { dirty, ctx };
			}

			button.$set(button_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(navbar.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formfield0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formfield1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formfield2.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(formfield3.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(button.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(navbar.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formfield0.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formfield1.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formfield2.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(formfield3.$$.fragment, local);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(button.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(navbar, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formfield0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formfield1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formfield2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(formfield3);
			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(button);
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

const emailRegexp = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Sign_up", slots, []);
	let loading = false;
	let username = "";
	let email = "";
	let password = "";
	let password_confirmation = "";
	let license_accepted = false;
	let errors = {};

	const validateUsername = () => {
		if (!username) {
			$$invalidate(6, errors = {
				...errors,
				username: "Please choose a username"
			});

			return;
		}

		if (username.length < 4) {
			$$invalidate(6, errors = {
				...errors,
				username: "Please choose a username that has at least 4 characters"
			});

			return;
		}
	};

	const validateEmail = () => {
		if (!email) {
			$$invalidate(6, errors = {
				...errors,
				email: "Please tell us your email address"
			});

			return;
		}

		if (!emailRegexp.test(email)) {
			$$invalidate(6, errors = {
				...errors,
				email: "This does not look like a valid email address"
			});

			return;
		}
	};

	const validatePassword = () => {
		if (!password) {
			$$invalidate(6, errors = {
				...errors,
				password: "Please choose a password"
			});

			return;
		}

		if (password.length < 6) {
			$$invalidate(6, errors = {
				...errors,
				password: "Your password is too short. Please choose a password that's at least 5 characters long."
			});

			return;
		}

		if (!password_confirmation) {
			$$invalidate(6, errors = {
				...errors,
				password_confirmation: "Please verify your chosen password by repeating it"
			});

			return;
		}

		if (password !== password_confirmation) {
			$$invalidate(6, errors = {
				...errors,
				password_confirmation: "The passwords don't match"
			});

			return;
		}
	};

	const validateLicense = () => {
		if (!license_accepted) {
			$$invalidate(6, errors = {
				...errors,
				license: "You have to accept the agreements."
			});

			return;
		}

		if (username.length < 4) {
			$$invalidate(6, errors = {
				...errors,
				username: "Please choose a username that has at least 4 characters"
			});

			return;
		}
	};

	const handleTestingFakes = () => {
		if (window._test_fake_signup) {
			if (window._test_user_already_exists) {
				$$invalidate(6, errors = {
					...errors,
					_form: "User already exists. Please choose another username."
				});

				return;
			}
		}
	};

	let handleSignUp;
	const writable_props = [];

	Object_1.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Sign_up> was created with unknown prop '${key}'`);
	});

	function formfield0_value_binding(value) {
		username = value;
		$$invalidate(1, username);
	}

	function formfield1_value_binding(value) {
		email = value;
		$$invalidate(2, email);
	}

	function formfield2_value_binding(value) {
		password = value;
		$$invalidate(3, password);
	}

	function formfield3_value_binding(value) {
		password_confirmation = value;
		$$invalidate(4, password_confirmation);
	}

	function input_change_handler() {
		license_accepted = this.checked;
		$$invalidate(5, license_accepted);
	}

	$$self.$capture_state = () => ({
		db: _db_db_js__WEBPACK_IMPORTED_MODULE_1__["default"],
		settings: _settings__WEBPACK_IMPORTED_MODULE_2__["default"],
		NavBar: _components_NavBar_svelte__WEBPACK_IMPORTED_MODULE_3__["default"],
		Button: lluis_Button__WEBPACK_IMPORTED_MODULE_4__["default"],
		FormField: lluis_FormField__WEBPACK_IMPORTED_MODULE_5__["default"],
		loading,
		username,
		email,
		password,
		password_confirmation,
		license_accepted,
		errors,
		emailRegexp,
		validateUsername,
		validateEmail,
		validatePassword,
		validateLicense,
		handleTestingFakes,
		handleSignUp
	});

	$$self.$inject_state = $$props => {
		if ("loading" in $$props) $$invalidate(0, loading = $$props.loading);
		if ("username" in $$props) $$invalidate(1, username = $$props.username);
		if ("email" in $$props) $$invalidate(2, email = $$props.email);
		if ("password" in $$props) $$invalidate(3, password = $$props.password);
		if ("password_confirmation" in $$props) $$invalidate(4, password_confirmation = $$props.password_confirmation);
		if ("license_accepted" in $$props) $$invalidate(5, license_accepted = $$props.license_accepted);
		if ("errors" in $$props) $$invalidate(6, errors = $$props.errors);
		if ("handleSignUp" in $$props) $$invalidate(7, handleSignUp = $$props.handleSignUp);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*errors, username, email, password*/ 78) {
			$: {
				$$invalidate(7, handleSignUp = async () => {
					$$invalidate(0, loading = true);
					$$invalidate(6, errors = {});
					validateUsername();
					validateEmail();
					validatePassword();
					validateLicense();
					handleTestingFakes();
					const isFormValid = Object.keys(errors).length === 0;

					if (true) {
						if (window._test_fake_signup) {
							setTimeout(
								function () {
									if (isFormValid === true) {
										$$invalidate(0, loading = false);
										window.location = "/sign-up-success";
									} else {
										$$invalidate(0, loading = false);
									}
								},
								500
							);
						} else {
							if (isFormValid) {
								fetch(_settings__WEBPACK_IMPORTED_MODULE_2__["default"].database.signUpEndpoint, {
									method: "post",
									headers: { "Content-Type": "application/json" },
									body: JSON.stringify({ username, email, password })
								}).then(data => data.json()).then(({ success, error }) => {
									if (success) {
										$$invalidate(0, loading = false);
										window.location = "/sign-up-success";
									} else {
										$$invalidate(0, loading = false);

										if (error.code === "invalid-payload") {
											$$invalidate(6, errors = error.details);
										} else {
											$$invalidate(6, errors = { _form: "Server error" });
										}
									}
								});
							} else {
								$$invalidate(0, loading = false);
							}
						}
					}
				});
			}
		}
	};

	return [
		loading,
		username,
		email,
		password,
		password_confirmation,
		license_accepted,
		errors,
		handleSignUp,
		formfield0_value_binding,
		formfield1_value_binding,
		formfield2_value_binding,
		formfield3_value_binding,
		input_change_handler
	];
}

class Sign_up extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Sign_up",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Sign_up);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL3NpZ24tdXAuc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUM4QjtBQUNNO0FBQ2M7QUFDZjtBQUNNOzs7Ozs7MEJBOE9KLEdBQU0sSUFBQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2tFQUFoQixHQUFNLElBQUMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQUtsQixHQUFNLElBQUMsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztrRUFBWixHQUFNLElBQUMsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkEzQzFCLEdBQU07OztrQkFDTixHQUFRO3dDQUFSLEdBQVE7Ozs7Ozs7Ozs7Ozs7O3lCQUtSLEdBQU07OztlQUNOLEdBQUs7cUNBQUwsR0FBSzs7Ozs7Ozs7Ozs7Ozs7O3lCQU1MLEdBQU07OztrQkFDTixHQUFRO3dDQUFSLEdBQVE7Ozs7Ozs7Ozs7Ozs7Ozt5QkFNUixHQUFNOzs7K0JBQ04sR0FBcUI7cURBQXJCLEdBQXFCOzs7Ozs0QkFnQjdCLEdBQU0sSUFBQyxTQUFTLEtBQUssSUFBSTs0QkFLM0IsR0FBTSxJQUFDLEtBQUssSUFBSSxJQUFJOzs7Ozs7Ozs7Ozs7OzsyRkFLWixHQUFZLHVCQUFaLEdBQVk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0NBakJGLEdBQWdCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2dHQXJDUixHQUFZLHVCQUFaLEdBQVk7Ozs7Ozs7Ozs7Ozs7O3lFQU81QixHQUFNOzs7OzRDQUNOLEdBQVE7Ozs7Ozt5RUFLUixHQUFNOzs7O3lDQUNOLEdBQUs7Ozs7Ozt5RUFNTCxHQUFNOzs7OzRDQUNOLEdBQVE7Ozs7Ozt5RUFNUixHQUFNOzs7O3lEQUNOLEdBQXFCOzs7Ozs7O3lDQVNiLEdBQWdCOzs7a0JBT2hDLEdBQU0sSUFBQyxTQUFTLEtBQUssSUFBSTs7Ozs7Ozs7Ozs7OztrQkFLM0IsR0FBTSxJQUFDLEtBQUssSUFBSSxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUF2T3ZCLFdBQVcsR0FBRyx3SEFBd0g7Ozs7O0tBVHhJLE9BQU8sR0FBRyxLQUFLO0tBRWYsUUFBUSxHQUFHLEVBQUU7S0FDYixLQUFLLEdBQUcsRUFBRTtLQUNWLFFBQVEsR0FBRyxFQUFFO0tBQ2IscUJBQXFCLEdBQUcsRUFBRTtLQUMxQixnQkFBZ0IsR0FBRyxLQUFLO0tBQ3hCLE1BQU07O09BSUosZ0JBQWdCO09BQ2YsUUFBUTttQkFDWCxNQUFNO09BQ0QsTUFBTTtJQUNULFFBQVEsRUFBRSwwQkFBMEI7Ozs7OztNQU1wQyxRQUFRLENBQUMsTUFBTSxHQUFHLENBQUM7bUJBQ3JCLE1BQU07T0FDRCxNQUFNO0lBQ1QsUUFBUSxFQUFFLHlEQUF5RDs7Ozs7OztPQU9uRSxhQUFhO09BQ1osS0FBSzttQkFDUixNQUFNO09BQ0QsTUFBTTtJQUNULEtBQUssRUFBRSxtQ0FBbUM7Ozs7OztPQU16QyxXQUFXLENBQUMsSUFBSSxDQUFDLEtBQUs7bUJBQ3pCLE1BQU07T0FDRCxNQUFNO0lBQ1QsS0FBSyxFQUFFLCtDQUErQzs7Ozs7OztPQU90RCxnQkFBZ0I7T0FDZixRQUFRO21CQUNYLE1BQU07T0FDRCxNQUFNO0lBQ1QsUUFBUSxFQUFFLDBCQUEwQjs7Ozs7O01BTXBDLFFBQVEsQ0FBQyxNQUFNLEdBQUcsQ0FBQzttQkFDckIsTUFBTTtPQUNELE1BQU07SUFDVCxRQUFRLEVBQ04seUZBQXlGOzs7Ozs7T0FNMUYscUJBQXFCO21CQUN4QixNQUFNO09BQ0QsTUFBTTtJQUNULHFCQUFxQixFQUNuQixvREFBb0Q7Ozs7OztNQU10RCxRQUFRLEtBQUsscUJBQXFCO21CQUNwQyxNQUFNO09BQ0QsTUFBTTtJQUNULHFCQUFxQixFQUFFLDJCQUEyQjs7Ozs7OztPQU9sRCxlQUFlO09BQ2QsZ0JBQWdCO21CQUNuQixNQUFNO09BQ0QsTUFBTTtJQUNULE9BQU8sRUFBRSxvQ0FBb0M7Ozs7OztNQU03QyxRQUFRLENBQUMsTUFBTSxHQUFHLENBQUM7bUJBQ3JCLE1BQU07T0FDRCxNQUFNO0lBQ1QsUUFBUSxFQUFFLHlEQUF5RDs7Ozs7OztPQU9uRSxrQkFBa0I7TUFDbEIsTUFBTSxDQUFDLGlCQUFpQjtPQUN0QixNQUFNLENBQUMseUJBQXlCO29CQUNsQyxNQUFNO1FBQ0QsTUFBTTtLQUNULEtBQUssRUFBRSxzREFBc0Q7Ozs7Ozs7O0tBT2pFLFlBQVk7Ozs7Ozs7O0VBNEVHLFFBQVE7Ozs7O0VBTVIsS0FBSzs7Ozs7RUFPTCxRQUFROzs7OztFQU9SLHFCQUFxQjs7Ozs7RUFTYixnQkFBZ0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7R0F4RzNDLENBQUM7b0JBQ0MsWUFBWTtxQkFDVixPQUFPLEdBQUcsSUFBSTtxQkFDZCxNQUFNO0tBQ04sZ0JBQWdCO0tBQ2hCLGFBQWE7S0FDYixnQkFBZ0I7S0FDaEIsZUFBZTtLQUNmLGtCQUFrQjtXQUNaLFdBQVcsR0FBRyxNQUFNLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxNQUFNLEtBQUssQ0FBQzs7U0FFaEQsSUFBd0I7VUFDdEIsTUFBTSxDQUFDLGlCQUFpQjtPQUMxQixVQUFVOzthQUNKLFdBQVcsS0FBSyxJQUFJOzBCQUN0QixPQUFPLEdBQUcsS0FBSztVQUNmLE1BQU0sQ0FBQyxRQUFRLEdBQUcsa0JBQWtCOzswQkFFcEMsT0FBTyxHQUFHLEtBQUs7OztRQUVoQixHQUFHOzs7V0FFRixXQUFXO1FBQ2IsS0FBSyxDQUFDLGlEQUFRLENBQUMsUUFBUSxDQUFDLGNBQWM7U0FDcEMsTUFBTSxFQUFFLE1BQU07U0FDZCxPQUFPLElBQ0wsY0FBYyxFQUFFLGtCQUFrQjtTQUVwQyxJQUFJLEVBQUUsSUFBSSxDQUFDLFNBQVMsR0FDbEIsUUFBUSxFQUNSLEtBQUssRUFDTCxRQUFRO1dBR1QsSUFBSSxDQUFFLElBQUksSUFBSyxJQUFJLENBQUMsSUFBSSxJQUN4QixJQUFJLElBQUksT0FBTyxFQUFFLEtBQUs7YUFDakIsT0FBTzswQkFDVCxPQUFPLEdBQUcsS0FBSztVQUNmLE1BQU0sQ0FBQyxRQUFRLEdBQUcsa0JBQWtCOzswQkFFcEMsT0FBTyxHQUFHLEtBQUs7O2NBQ1gsS0FBSyxDQUFDLElBQUksS0FBSyxpQkFBaUI7MkJBQ2xDLE1BQU0sR0FBRyxLQUFLLENBQUMsT0FBTzs7MkJBRXRCLE1BQU0sS0FBSyxLQUFLLEVBQUUsY0FBYzs7Ozs7d0JBS3hDLE9BQU8sR0FBRyxLQUFLIiwiZmlsZSI6ImFlYmU5ZjBmMmYxMDg2NWJmNGJkL3NpZ24kNDV1cC5zaWduJDQ1dXAuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBpbXBvcnQgZGIgZnJvbSBcIi4uL2RiL2RiLmpzXCJcbiAgaW1wb3J0IHNldHRpbmdzIGZyb20gXCIuLi9zZXR0aW5nc1wiXG4gIGltcG9ydCBOYXZCYXIgZnJvbSBcIi4uL2NvbXBvbmVudHMvTmF2QmFyLnN2ZWx0ZVwiXG4gIGltcG9ydCBCdXR0b24gZnJvbSBcImxsdWlzL0J1dHRvblwiXG4gIGltcG9ydCBGb3JtRmllbGQgZnJvbSBcImxsdWlzL0Zvcm1GaWVsZFwiXG5cbiAgbGV0IGxvYWRpbmcgPSBmYWxzZVxuXG4gIGxldCB1c2VybmFtZSA9IFwiXCJcbiAgbGV0IGVtYWlsID0gXCJcIlxuICBsZXQgcGFzc3dvcmQgPSBcIlwiXG4gIGxldCBwYXNzd29yZF9jb25maXJtYXRpb24gPSBcIlwiXG4gIGxldCBsaWNlbnNlX2FjY2VwdGVkID0gZmFsc2VcbiAgbGV0IGVycm9ycyA9IHt9XG5cbiAgY29uc3QgZW1haWxSZWdleHAgPSAvXigoW148PigpXFxbXFxdXFwuLDs6XFxzQFxcXCJdKyhcXC5bXjw+KClcXFtcXF1cXC4sOzpcXHNAXFxcIl0rKSopfChcXFwiLitcXFwiKSlAKChbXjw+KClbXFxdXFwuLDs6XFxzQFxcXCJdK1xcLikrW148PigpW1xcXVxcLiw7Olxcc0BcXFwiXXsyLH0pJC9pXG5cbiAgY29uc3QgdmFsaWRhdGVVc2VybmFtZSA9ICgpID0+IHtcbiAgICBpZiAoIXVzZXJuYW1lKSB7XG4gICAgICBlcnJvcnMgPSB7XG4gICAgICAgIC4uLmVycm9ycyxcbiAgICAgICAgdXNlcm5hbWU6IFwiUGxlYXNlIGNob29zZSBhIHVzZXJuYW1lXCIsXG4gICAgICB9XG5cbiAgICAgIHJldHVyblxuICAgIH1cblxuICAgIGlmICh1c2VybmFtZS5sZW5ndGggPCA0KSB7XG4gICAgICBlcnJvcnMgPSB7XG4gICAgICAgIC4uLmVycm9ycyxcbiAgICAgICAgdXNlcm5hbWU6IFwiUGxlYXNlIGNob29zZSBhIHVzZXJuYW1lIHRoYXQgaGFzIGF0IGxlYXN0IDQgY2hhcmFjdGVyc1wiLFxuICAgICAgfVxuXG4gICAgICByZXR1cm5cbiAgICB9XG4gIH1cblxuICBjb25zdCB2YWxpZGF0ZUVtYWlsID0gKCkgPT4ge1xuICAgIGlmICghZW1haWwpIHtcbiAgICAgIGVycm9ycyA9IHtcbiAgICAgICAgLi4uZXJyb3JzLFxuICAgICAgICBlbWFpbDogXCJQbGVhc2UgdGVsbCB1cyB5b3VyIGVtYWlsIGFkZHJlc3NcIixcbiAgICAgIH1cblxuICAgICAgcmV0dXJuXG4gICAgfVxuXG4gICAgaWYgKCFlbWFpbFJlZ2V4cC50ZXN0KGVtYWlsKSkge1xuICAgICAgZXJyb3JzID0ge1xuICAgICAgICAuLi5lcnJvcnMsXG4gICAgICAgIGVtYWlsOiBcIlRoaXMgZG9lcyBub3QgbG9vayBsaWtlIGEgdmFsaWQgZW1haWwgYWRkcmVzc1wiLFxuICAgICAgfVxuXG4gICAgICByZXR1cm5cbiAgICB9XG4gIH1cblxuICBjb25zdCB2YWxpZGF0ZVBhc3N3b3JkID0gKCkgPT4ge1xuICAgIGlmICghcGFzc3dvcmQpIHtcbiAgICAgIGVycm9ycyA9IHtcbiAgICAgICAgLi4uZXJyb3JzLFxuICAgICAgICBwYXNzd29yZDogXCJQbGVhc2UgY2hvb3NlIGEgcGFzc3dvcmRcIixcbiAgICAgIH1cblxuICAgICAgcmV0dXJuXG4gICAgfVxuXG4gICAgaWYgKHBhc3N3b3JkLmxlbmd0aCA8IDYpIHtcbiAgICAgIGVycm9ycyA9IHtcbiAgICAgICAgLi4uZXJyb3JzLFxuICAgICAgICBwYXNzd29yZDpcbiAgICAgICAgICBcIllvdXIgcGFzc3dvcmQgaXMgdG9vIHNob3J0LiBQbGVhc2UgY2hvb3NlIGEgcGFzc3dvcmQgdGhhdCdzIGF0IGxlYXN0IDUgY2hhcmFjdGVycyBsb25nLlwiLFxuICAgICAgfVxuXG4gICAgICByZXR1cm5cbiAgICB9XG5cbiAgICBpZiAoIXBhc3N3b3JkX2NvbmZpcm1hdGlvbikge1xuICAgICAgZXJyb3JzID0ge1xuICAgICAgICAuLi5lcnJvcnMsXG4gICAgICAgIHBhc3N3b3JkX2NvbmZpcm1hdGlvbjpcbiAgICAgICAgICBcIlBsZWFzZSB2ZXJpZnkgeW91ciBjaG9zZW4gcGFzc3dvcmQgYnkgcmVwZWF0aW5nIGl0XCIsXG4gICAgICB9XG5cbiAgICAgIHJldHVyblxuICAgIH1cblxuICAgIGlmIChwYXNzd29yZCAhPT0gcGFzc3dvcmRfY29uZmlybWF0aW9uKSB7XG4gICAgICBlcnJvcnMgPSB7XG4gICAgICAgIC4uLmVycm9ycyxcbiAgICAgICAgcGFzc3dvcmRfY29uZmlybWF0aW9uOiBcIlRoZSBwYXNzd29yZHMgZG9uJ3QgbWF0Y2hcIixcbiAgICAgIH1cblxuICAgICAgcmV0dXJuXG4gICAgfVxuICB9XG5cbiAgY29uc3QgdmFsaWRhdGVMaWNlbnNlID0gKCkgPT4ge1xuICAgIGlmICghbGljZW5zZV9hY2NlcHRlZCkge1xuICAgICAgZXJyb3JzID0ge1xuICAgICAgICAuLi5lcnJvcnMsXG4gICAgICAgIGxpY2Vuc2U6IFwiWW91IGhhdmUgdG8gYWNjZXB0IHRoZSBhZ3JlZW1lbnRzLlwiLFxuICAgICAgfVxuXG4gICAgICByZXR1cm5cbiAgICB9XG5cbiAgICBpZiAodXNlcm5hbWUubGVuZ3RoIDwgNCkge1xuICAgICAgZXJyb3JzID0ge1xuICAgICAgICAuLi5lcnJvcnMsXG4gICAgICAgIHVzZXJuYW1lOiBcIlBsZWFzZSBjaG9vc2UgYSB1c2VybmFtZSB0aGF0IGhhcyBhdCBsZWFzdCA0IGNoYXJhY3RlcnNcIixcbiAgICAgIH1cblxuICAgICAgcmV0dXJuXG4gICAgfVxuICB9XG5cbiAgY29uc3QgaGFuZGxlVGVzdGluZ0Zha2VzID0gKCkgPT4ge1xuICAgIGlmICh3aW5kb3cuX3Rlc3RfZmFrZV9zaWdudXApIHtcbiAgICAgIGlmICh3aW5kb3cuX3Rlc3RfdXNlcl9hbHJlYWR5X2V4aXN0cykge1xuICAgICAgICBlcnJvcnMgPSB7XG4gICAgICAgICAgLi4uZXJyb3JzLFxuICAgICAgICAgIF9mb3JtOiBcIlVzZXIgYWxyZWFkeSBleGlzdHMuIFBsZWFzZSBjaG9vc2UgYW5vdGhlciB1c2VybmFtZS5cIixcbiAgICAgICAgfVxuICAgICAgICByZXR1cm5cbiAgICAgIH1cbiAgICB9XG4gIH1cblxuICBsZXQgaGFuZGxlU2lnblVwXG4gICQ6IHtcbiAgICBoYW5kbGVTaWduVXAgPSBhc3luYyAoKSA9PiB7XG4gICAgICBsb2FkaW5nID0gdHJ1ZVxuICAgICAgZXJyb3JzID0ge31cbiAgICAgIHZhbGlkYXRlVXNlcm5hbWUoKVxuICAgICAgdmFsaWRhdGVFbWFpbCgpXG4gICAgICB2YWxpZGF0ZVBhc3N3b3JkKClcbiAgICAgIHZhbGlkYXRlTGljZW5zZSgpXG4gICAgICBoYW5kbGVUZXN0aW5nRmFrZXMoKVxuICAgICAgY29uc3QgaXNGb3JtVmFsaWQgPSBPYmplY3Qua2V5cyhlcnJvcnMpLmxlbmd0aCA9PT0gMFxuXG4gICAgICBpZiAocHJvY2Vzcy5icm93c2VyID09PSB0cnVlKSB7XG4gICAgICAgIGlmICh3aW5kb3cuX3Rlc3RfZmFrZV9zaWdudXApIHtcbiAgICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uICgpIHtcbiAgICAgICAgICAgIGlmIChpc0Zvcm1WYWxpZCA9PT0gdHJ1ZSkge1xuICAgICAgICAgICAgICBsb2FkaW5nID0gZmFsc2VcbiAgICAgICAgICAgICAgd2luZG93LmxvY2F0aW9uID0gXCIvc2lnbi11cC1zdWNjZXNzXCJcbiAgICAgICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICAgIGxvYWRpbmcgPSBmYWxzZVxuICAgICAgICAgICAgfVxuICAgICAgICAgIH0sIDUwMClcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICBpZiAoaXNGb3JtVmFsaWQpIHtcbiAgICAgICAgICAgIGZldGNoKHNldHRpbmdzLmRhdGFiYXNlLnNpZ25VcEVuZHBvaW50LCB7XG4gICAgICAgICAgICAgIG1ldGhvZDogXCJwb3N0XCIsXG4gICAgICAgICAgICAgIGhlYWRlcnM6IHtcbiAgICAgICAgICAgICAgICBcIkNvbnRlbnQtVHlwZVwiOiBcImFwcGxpY2F0aW9uL2pzb25cIixcbiAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkoe1xuICAgICAgICAgICAgICAgIHVzZXJuYW1lLFxuICAgICAgICAgICAgICAgIGVtYWlsLFxuICAgICAgICAgICAgICAgIHBhc3N3b3JkLFxuICAgICAgICAgICAgICB9KSxcbiAgICAgICAgICAgIH0pXG4gICAgICAgICAgICAgIC50aGVuKChkYXRhKSA9PiBkYXRhLmpzb24oKSlcbiAgICAgICAgICAgICAgLnRoZW4oKHsgc3VjY2VzcywgZXJyb3IgfSkgPT4ge1xuICAgICAgICAgICAgICAgIGlmIChzdWNjZXNzKSB7XG4gICAgICAgICAgICAgICAgICBsb2FkaW5nID0gZmFsc2VcbiAgICAgICAgICAgICAgICAgIHdpbmRvdy5sb2NhdGlvbiA9IFwiL3NpZ24tdXAtc3VjY2Vzc1wiXG4gICAgICAgICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgICAgICAgIGxvYWRpbmcgPSBmYWxzZVxuICAgICAgICAgICAgICAgICAgaWYgKGVycm9yLmNvZGUgPT09IFwiaW52YWxpZC1wYXlsb2FkXCIpIHtcbiAgICAgICAgICAgICAgICAgICAgZXJyb3JzID0gZXJyb3IuZGV0YWlsc1xuICAgICAgICAgICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgICAgICAgICAgZXJyb3JzID0geyBfZm9ybTogXCJTZXJ2ZXIgZXJyb3JcIiB9XG4gICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgICB9KVxuICAgICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICBsb2FkaW5nID0gZmFsc2VcbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICB9XG4gIH1cbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TaWduIHVwIC0gTGlicmVMaW5nbzwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48TmF2QmFyIGRhcmsgLz5cblxuPHNlY3Rpb24gY2xhc3M9XCJzZWN0aW9uXCI+XG5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuXG4gICAgPGZvcm0gb246c3VibWl0fHByZXZlbnREZWZhdWx0PVwie2hhbmRsZVNpZ25VcH1cIj5cbiAgICAgIDxoMiBjbGFzcz1cImlzLXNpemUtMlwiPlNpZ24gdXA8L2gyPlxuXG4gICAgICA8Rm9ybUZpZWxkXG4gICAgICAgIG5hbWU9XCJVc2VybmFtZVwiXG4gICAgICAgIGljb249XCJ1c2VyXCJcbiAgICAgICAgaWQ9XCJ1c2VybmFtZVwiXG4gICAgICAgIGZvcm1TdGF0dXM9XCJ7ZXJyb3JzfVwiXG4gICAgICAgIGJpbmQ6dmFsdWU9XCJ7dXNlcm5hbWV9XCIgLz5cbiAgICAgIDxGb3JtRmllbGRcbiAgICAgICAgbmFtZT1cIkVtYWlsXCJcbiAgICAgICAgaWNvbj1cImVudmVsb3BlXCJcbiAgICAgICAgaWQ9XCJlbWFpbFwiXG4gICAgICAgIGZvcm1TdGF0dXM9XCJ7ZXJyb3JzfVwiXG4gICAgICAgIGJpbmQ6dmFsdWU9XCJ7ZW1haWx9XCIgLz5cbiAgICAgIDxGb3JtRmllbGRcbiAgICAgICAgbmFtZT1cIlBhc3N3b3JkXCJcbiAgICAgICAgaWNvbj1cImxvY2tcIlxuICAgICAgICBpZD1cInBhc3N3b3JkXCJcbiAgICAgICAgdHlwZT1cInBhc3N3b3JkXCJcbiAgICAgICAgZm9ybVN0YXR1cz1cIntlcnJvcnN9XCJcbiAgICAgICAgYmluZDp2YWx1ZT1cIntwYXNzd29yZH1cIiAvPlxuICAgICAgPEZvcm1GaWVsZFxuICAgICAgICBuYW1lPVwiUmVwZWF0IHBhc3N3b3JkXCJcbiAgICAgICAgaWNvbj1cImxvY2tcIlxuICAgICAgICBpZD1cInBhc3N3b3JkX2NvbmZpcm1hdGlvblwiXG4gICAgICAgIHR5cGU9XCJwYXNzd29yZFwiXG4gICAgICAgIGZvcm1TdGF0dXM9XCJ7ZXJyb3JzfVwiXG4gICAgICAgIGJpbmQ6dmFsdWU9XCJ7cGFzc3dvcmRfY29uZmlybWF0aW9ufVwiIC8+XG5cbiAgICAgIDxkaXYgY2xhc3M9XCJmaWVsZFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29udHJvbFwiPlxuICAgICAgICAgIDxsYWJlbCBjbGFzcz1cImNoZWNrYm94XCI+XG4gICAgICAgICAgICA8aW5wdXRcbiAgICAgICAgICAgICAgdHlwZT1cImNoZWNrYm94XCJcbiAgICAgICAgICAgICAgbmFtZT1cImxpY2Vuc2VcIlxuICAgICAgICAgICAgICBpZD1cImxpY2Vuc2VcIlxuICAgICAgICAgICAgICBiaW5kOmNoZWNrZWQ9XCJ7bGljZW5zZV9hY2NlcHRlZH1cIiAvPlxuICAgICAgICAgICAgSSBhZ3JlZSB0byB0aGVcbiAgICAgICAgICAgIDxhIGhyZWY9XCIvdG9zXCI+VGVybXMgYW5kIENvbmRpdGlvbnM8L2E+XG4gICAgICAgICAgICBhbmQgdGhlXG4gICAgICAgICAgICA8YSBocmVmPVwiL2xpY2Vuc2VcIj5HTlUgQWZmZXJvIEdlbmVyYWwgUHVibGljIExpY2Vuc2U8L2E+XG4gICAgICAgICAgPC9sYWJlbD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIHsjaWYgZXJyb3JzWydsaWNlbnNlJ10gIT0gbnVsbH1cbiAgICAgICAgICA8cCBjbGFzcz1cImhlbHAgaXMtZGFuZ2VyXCI+e2Vycm9yc1snbGljZW5zZSddfTwvcD5cbiAgICAgICAgey9pZn1cbiAgICAgIDwvZGl2PlxuXG4gICAgICB7I2lmIGVycm9ycy5fZm9ybSAhPSBudWxsfVxuICAgICAgICA8cCBjbGFzcz1cImhlbHAgaXMtZGFuZ2VyXCI+e2Vycm9ycy5fZm9ybX08L3A+XG4gICAgICB7L2lmfVxuXG4gICAgICA8QnV0dG9uXG4gICAgICAgIG9uOmNsaWNrPVwie2hhbmRsZVNpZ25VcH1cIlxuICAgICAgICB7bG9hZGluZ31cbiAgICAgICAgYXNIcmVmPVwiL3NpZ24tdXAtc3VjY2Vzc1wiXG4gICAgICAgIHN1Ym1pdD5cbiAgICAgICAgU2lnbiB1cFxuICAgICAgPC9CdXR0b24+XG4gICAgPC9mb3JtPlxuICA8L2Rpdj5cblxuPC9zZWN0aW9uPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==